### ISSUE TITLE
adding IRIs to the ontological terms

### ISSUE THREAD

**Issue by lzehl** [HumanBrainProject/openMINDS_controlledTerms#1]
@tgbugs: could you add the IRI to the corresponding ontological term for each term (JSON_LD) in v1.0-terminologies, or let me know where I can best check for them? The latter might be more convenient for you because the v1.0-terminologies will be extended step-by-step. Thanks in advance!

**Comment by tgbugs** [comment]
What key should they go under? Related ontology seems like it would point to the whole pato ontology rather than the individual term, does it really mean relatedOntologyTerm, and if so should it be changed for clarity?

You can search scigraph here https://scicrunch.org/browse/terminology/male. I'd use the PATO terms for this.

**Comment by lzehl** [comment]
@tgbugs thanks for your quick reply. If you think it adds more clarity we can change the property to "relatedOntologyTerm"  or "correspondingOntologyTerm" or "matchingOntologyTerm" or maybe even just "ontologyTerm" ? What do you think?

**Comment by lzehl** [comment]
@tgbugs am I correct if I assume that I can infer which ontology you used from the identifier currently stored in the KG for all the ontological terms already in there?

**Comment by tgbugs** [comment]
I think `ontologyTerm` or `ontologyIdentifier` would work. You can usually infer which ontology it came from but not always. For example UBERON and PATO terms you can, but for BIRNLEX you can't because there are multiple possible files that they are defined in.

**Comment by lzehl** [comment]
I like the `ontologyIdentifier`. @UlrikeS91 this need to be also change in SANDS

**Comment by lzehl** [comment]
this issue was solved. I'll close it now.
