### ISSUE TITLE
Add other cell types to TissueSample origin?

### ISSUE THREAD

**Issue by amkvello** [HumanBrainProject/openMINDS_controlledTerms#104]
I suggest to add

- endothelial cell
- mural cell

to the "origin" controlled terms for TissueSample and TissueSampleCollection.

There might be other non-neuronal / non-glial cells that we want to add as well (that I cannot think of atm).

**Comment by lzehl** [comment]
@amkvello thanks for making the request. To clarify you mean to add "vascular endothelial cell" (endothelial cell) and "vascular smooth muscle cell" (mural cell) as controlled terms to cell type, correct?

**Comment by amkvello** [comment]
Yes, for cell type is what I meant. Sorry for being a bit unclear :)

**Comment by lzehl** [comment]
don't worry. I think they both can be added. @tgbugs : there are multiple options in InterLex for "endothelial cell". Which one should we link? And I could not find an entry for mural cell in InterLex. Did I miss it?

**Comment by amkvello** [comment]
@lzehl, I was not familiar with "mural cell" from before, only "vascular smooth muscle cell". Mural cell was stated by the data provider (and used in the file naming).

**Comment by tgbugs** [comment]
I would go with vascular endothelial cell.

The vascular smooth muscle cell
```
	CL:0000359
		abbreviations: []
		acronyms: []
		categories: []
		definitions: ['A smooth muscle cell assocatiated with the vasculature.']
		deprecated: False
		iri: http://purl.obolibrary.org/obo/CL_0000359
		labels: ['vascular associated smooth muscle cell']
		synonyms: ['VSMC', 'vascular smooth muscle cell']

```

**Comment by lzehl** [comment]
integrated :)
