### ISSUE TITLE
Request for new technique

### ISSUE THREAD

**Issue by MaaikevS** [HumanBrainProject/openMINDS_controlledTerms#112]
Hi,

Could you please add RNA sequencing as a new technique? At the moment only single-cell RNA sequencing exists and the Data Provider does not think this is a suitable technique for his dataset. He would like to have "normal" RNA sequencing on the card.

Many thanks,
Maaike

**Comment by UlrikeS91** [comment]
That sound reasonable and I also found an InterLex entry for it (http://uri.interlex.org/ilx_0782092), so I'll prep a PR :)

**Comment by MaaikevS** [comment]
Thanks!
