### ISSUE TITLE
New tissue sample states attributes

### ISSUE THREAD

**Issue by MaaikevS** [HumanBrainProject/openMINDS_controlledTerms#133]
It would be good to have some additional tissue sample states, for example:

1. Fixated 
2. Not fixated / "fresh"

@UlrikeS91 @lzehl Let me know your thoughts and I would be happy to add them if you agree!

**Comment by lzehl** [comment]
These two attributes are both already listed in tissueSampleAttribute.
fixated: https://github.com/HumanBrainProject/openMINDS_controlledTerms/blob/v1/instances/tissueSampleAttribute/fixated.jsonld
"fresh" as untreated: https://github.com/HumanBrainProject/openMINDS_controlledTerms/blob/v1/instances/tissueSampleAttribute/untreated.jsonld

**Comment by lzehl** [comment]
@MaaikevS does this fit your needs?

**Comment by MaaikevS** [comment]
I actually meant attributes indeed, so this is perfect. I must have overlooked them. Sorry about that!
