### ISSUE TITLE
New schema for Administration Type

### ISSUE THREAD

**Issue by MaaikevS** [HumanBrainProject/openMINDS_controlledTerms#135]
Could we add a schema for administration type with the following controlled instances?
- oral
- subcutaneous 
- interperitoneal 
- intravenous

Any thoughts?

**Comment by lzehl** [comment]
@MaaikevS yes that's a good idea in regard of openMINDS extensions for surgeries or treatments. Do you want to make a PR for it or should we take over?

**Comment by MaaikevS** [comment]
I will send a pull request in a minute :)
