### ISSUE TITLE
New deviceType suggestions

### ISSUE THREAD

**Issue by MaaikevS** [HumanBrainProject/openMINDS_controlledTerms#136]
Would it be possible to extend the number of instances for "DeviceType"?

For example with:
- microscope
- vibratome
- microtome

**Comment by UlrikeS91** [comment]
Sorry that nobody has reacted to your request. @lzehl, this was also discussed in relation to the ephys extension. Those can (and should be) added. The controlledTerms schema exists, and it has been added as a terminology, but the instances folder does not exist yet. 
@MaaikevS would you be able to prepare the instances in a new deviceType folder (here: https://github.com/HumanBrainProject/openMINDS_controlledTerms/tree/v1/instances)?

**Comment by lzehl** [comment]
@MaaikevS @UlrikeS91 yes please go ahead and add instances for DeviceType. 
@Peyman-N please provide a list of DeviceTypes that you need (I assume for example "MRI scanner", or "PET scanner", or "Amplifier").

**Comment by MaaikevS** [comment]
@UlrikeS91 @lzehl I was under the impression that deviceType already had a folder (there is the instance "magnetic resonance imaging scanner" for deviceType in the KGE). This is probably old then; the info can be converted into a new openMINDS instance and the instance can be removed from the KGE (it is not attached to anything yet)

I will start with the following device types:
- microscope
- vibratome
- microtome
- MRI scanner
- PET scanner
- Amplifier

@Peyman-N please let me know what else needs to be added.

**Comment by MaaikevS** [comment]
Actually, I think PET is more a method than a device, since it is typically combined with CT (PET/CT) or MRI (PET/MRI). So perhaps we want to consider adding the combination instead of PET scanner. Thoughts?

**Comment by lzehl** [comment]
as far as I researched there are also PET standalone scanners. But I agree we should add the more common ones as well PET/CT scanner (which is not purely a combination of two devices but one device able to perform both techniques as far as I know).

**Comment by lzehl** [comment]
closed with #176
