### ISSUE TITLE
New analysis technique in bioinformatics

### ISSUE THREAD

**Issue by MaaikevS** [HumanBrainProject/openMINDS_controlledTerms#139]
Would it be possible to add weighted gene co-expression network analysis as a technique?

Weighted gene co-expression network analysis (WGCNA) is a bioinformatics application for exploring the relationships between different gene sets (modules), or between gene sets and clinical features (Langfelder and Horvath, 2008).

**Comment by lzehl** [comment]
@MaaikevS thanks for this suggestion. From what I see WGCNA is the name of an R package. I would therefore rather register "weighted correlation network analysis" which seems to be an analysis technique also usable on other data than gene expression

**Comment by MaaikevS** [comment]
@lzehl You are right that WGCNA is indeed also the name of an R package, but it also seems to be a very common analysis when it comes to gene expression. However, it is not limited to gene expression alone as you point out. I think there is a good chance that most datasets shared in Neuroscience will apply it to gene expression, but we cannot be certain. Therefore including a more general form instead is not a bad idea. Should I make a PR for this?

**Comment by lzehl** [comment]
yes please :)
