### ISSUE TITLE
Unused types

### ISSUE THREAD

**Issue by olinux** [HumanBrainProject/openMINDS_controlledTerms#14]
The types 
https://openminds.ebrains.eu/controlledTerms/SoftwareFeatureCategory
and
https://openminds.ebrains.eu/controlledTerms/StudyTargetType
seem to be unused by both core and SANDS. Maybe they should be removed?

**Comment by olinux** [comment]
Comment for StudyTargetType: This is linked to the issue #11 and should be solved after accepting pull request #17

**Comment by lzehl** [comment]
@olinux thanks for reporting this. If they are unused intentionally we should remove them. I'll double check if it is not a spelling issue or if they were planned and then forgotten. But I think it was just missed to delete them after the last metadata model changes.

**Comment by lzehl** [comment]
This issue was solved in #25
