### ISSUE TITLE
Add new terminology - subcellular entity

### ISSUE THREAD

**Issue by UlrikeS91** [HumanBrainProject/openMINDS_controlledTerms#147]
As discussed offline with @MaaikevS and @lzehl, we should add a new terminology called "subcellular entity" ([http://uri.interlex.org/ilx_0111157](http://uri.interlex.org/base/ilx_0111157)). 

This would include controlled terms such as:
- (a)symmetric synapse
- neurites 
- nucleus
- mitochondrion
- etc.

@MaaikevS would you be able to take care of this? 

FYI @tgbugs

**Comment by MaaikevS** [comment]
@UlrikeS91 Yes, I will take care of this

**Comment by UlrikeS91** [comment]
We need some additional things here. Sorry about the delay. 

Generally, when a new terminology is added to the controlledTerms repo, the following 3 things have to be done:
1. Create the new controlled terms schema for the specific terminology (which has been done in PR #158)
2. Create the corresponding instances in the terminology folder (here: https://github.com/HumanBrainProject/openMINDS_controlledTerms/tree/v1/instances/terminology) 
3. Create at least one example instances for the new terminology. This way the folder exists and it is easier to understand what the terminology includes. The folder will be https://github.com/HumanBrainProject/openMINDS_controlledTerms/tree/v1/instances/subcellularEntity. The above mentioned examples could be added as such first instances there.

**Comment by MaaikevS** [comment]
@UlrikeS91 I will take care of this in the next few days. I have been delayed on openMINDS related developments because of last minute other tasks!

**Comment by MaaikevS** [comment]
@UlrikeS91 Number 1 and 2 of your list were already done a few weeks ago. Number 3 should be taken care of with PR #174

**Comment by UlrikeS91** [comment]
> @UlrikeS91 Number 1 and 2 of your list were already done a few weeks ago. Number 3 should be taken care of with PR #174

True. Sorry about that. I must have missed the instance in the terminology folder! Thanks for fixing the PR. I'll review it now.
