### ISSUE TITLE
rename wild_type into wildType

### ISSUE THREAD

**Issue by olinux** [HumanBrainProject/openMINDS_controlledTerms#15]
To be consistent, we should follow the lowerCamelCase syntax for everything in JSON(-LD).

https://github.com/HumanBrainProject/openMINDS_controlledTerms/blob/2400e43e873fbfadd9f776fa69bc541a86144c8a/terminologies/phenotype/wild_type.jsonld#L2

**Comment by lzehl** [comment]
@olinux : I agree! 

@UlrikeS91 : do you agree as well? why was it changed to "wild_type"?

**Comment by UlrikeS91** [comment]
Hmm, good question. I think the logic I followed was that the name is "wild type", so the jsonld should indicate the space. Not sure, why this was the most logical conclusion anymore...

Feel free to change it to `wildType`!

**Comment by olinux** [comment]
fixed
