### ISSUE TITLE
Add new service instance - OSD viewer

### ISSUE THREAD

**Issue by UlrikeS91** [HumanBrainProject/openMINDS_controlledTerms#152]
We are working on some additional service links for some dataset that will use a different tool than LocaliZoom, which is viewing any type of images without an atlas overlay or anything. @majpuc, could you please provide information about this tool so that we can add a new service instance for this tool, just like we have for LocaliZoom: https://github.com/HumanBrainProject/openMINDS_controlledTerms/blob/v1/instances/service/LocaliZoom.jsonld? 

Once I have that information, I can add the service that we will used in relation to the service links ☺️

**Comment by Majpuc** [comment]
{
  "@context": {
    "@vocab": "https://openminds.ebrains.eu/vocab/"
  },
  "@id": "https://openminds.ebrains.eu/instances/service/Multi-Image-OSd",
  "@type": "https://openminds.ebrains.eu/controlledTerms/Service",
  "definition": "Web application for viewing of series of high-resolution 2D images.",
  "description": "Multi-Image-OSd allows the viewing and exploring of high-resolution images.  For more information see: https://github.com/Neural-Systems-at-UIO/Multi-Image-OSd",
  "interlexIdentifier": null,
  "knowledgeSpaceLink": null,
  "name": "Multi-Image-OSd",
  "preferredOntologyIdentifier": null,
  "synonym": null
}

**Comment by MaaikevS** [comment]
I think we should push this if we want to move forward with the service links for this service. I would say the name probably has to be changed though.
