### ISSUE TITLE
correction of  openMINDS_controlledTerms/instances/service/LocaliZoom.jsonld 

### ISSUE THREAD

**Issue by Majpuc** [HumanBrainProject/openMINDS_controlledTerms#153]
Hi, 
I discovered a misunderstanding in the definition of the Localizoom viewer as service link and would like to correct it. It is confusing but we have Localizoom as a viewer only, the one used as service link and then the Localizoom sw that is allowing annotations.
Here would be the correct text:
{
  "@context": {
    "@vocab": "https://openminds.ebrains.eu/vocab/"
  },
  "@id": "https://openminds.ebrains.eu/instances/service/LocaliZoom",
  "@type": "https://openminds.ebrains.eu/controlledTerms/Service",
  "definition": "Web application for viewing of series of high-resolution 2D images that have been anchored to reference atlases.",
  "description": "LocaliZoom allows the viewing and exploring of high-resolution images with superimposed atlas overlays.",
  "interlexIdentifier": null,
  "knowledgeSpaceLink": null,
  "name": "LocaliZoom",
  "preferredOntologyIdentifier": null,
  "synonym": null
}

**Comment by lzehl** [comment]
@Majpuc is there in general a more lengthy description of LocaliZoom and documentation homepage links we should cover? It would be great to be a bit more detailed for the services are able to get these type of information. Could you support us here for LocaliZoom and the new one Multi-Image-OSd?

@UlrikeS91 FYI

**Comment by UlrikeS91** [comment]
I guess @Majpuc came across this because of #152. I can fix it in parallel to adding the new service.

**Comment by Majpuc** [comment]
yes, we have a Readthedocs for Localizoom:  [](https://localizoom.readthedocs.io/en/latest/index.htm)
https://localizoom.readthedocs.io/en/latest/index.htm
 The doc for Multi-Image OSd is coming soon.
