### ISSUE TITLE
Suggestions for genetic techniques

### ISSUE THREAD

**Issue by AnnaHilverling** [HumanBrainProject/openMINDS_controlledTerms#180]
Hi all,

I would like to start a discussion about the following methods:
- whole genome sequencing
- single-gene analysis / sequencing
- (protein) pathway analysis
- single nucleotide polymorphism analysis 

--> Should these methods be registered as individual techniques?

Maybe single nucleotid polymorphism fits better to study target, but I do not know in which category this should be registered...

Thank you!

**Comment by lzehl** [comment]
@AnnaHilverling thanks for raising the issue. 

@tgbugs could you have a look at this? See my comments below:
I know whole genome sequencing is registered in InterLex. 
I found some comparison paper between single-gene anaysis vs gene set analysis (https://www.frontiersin.org/articles/10.3389/fgene.2020.00654/full), but no clear one sentence definition. 
I found pathway analysis in InterLex but I'm not sure that is sufficient for proteins. 
I would say single nucleotide polymorphism should be registered as study target in combination with a sequencing technique.

**Comment by lzehl** [comment]
@AnnaHilverling and @tgbugs 

I've added now:
+ DNA sequencing
+ single gene analysis
+ whole genome sequencing
+ pathway analysis
+ single nucleotide polymorphism detection

**Comment by UlrikeS91** [comment]
This seems to be resolve. I'll close it. If that was wrong, please reopen it.
