### ISSUE TITLE
New molecular entities

### ISSUE THREAD

**Issue by MaaikevS** [HumanBrainProject/openMINDS_controlledTerms#185]
Here is a list of molecular entities that would be good to add. Naming convention (abbreviation vs full name) needs to be decided on.

I would like to propose to do this in stages and prioritise the more pressing ones first. Please feel free to indicate which ones need prioritisation.

name | synonym | interlex | preferredOntology | KnowledgeSpace
-- | -- | -- | -- | --
4-DAMP methobromide |   | http://uri.interlex.org/base/ilx_0686819 | http://id.nlm.nih.gov/mesh/2018/M0125168, https://ncimeta.nci.nih.gov/ncimbrowser/ConceptReport.jsp?dictionary=NCI%20Metathesaurus&code=C0096896 |  
acetylcholine | Ach | http://uri.interlex.org/ilx_0100240 | http://uri.neuinfo.org/nif/nifstd/sao185580330 |  
AgRP | agouti-related protein agouti-related peptide AGRP ART AGRT |   | http://purl.obolibrary.org/obo/PR_000003846 | https://knowledge-space.org/wiki/PR:000003846#agouti-related-protein
APV | (2R)-amino-5-phosphonovaleric acid AP5 | http://uri.neuinfo.org/nif/nifstd/nlx_94485 |   |  
Cav2.1 channel | P/Q voltage-dependent calcium channel |   |   |  
CGP 54626 |   | http://uri.interlex.org/ilx_0439399 | http://id.nlm.nih.gov/mesh/2018/M0279326 |  
cholecystokinin | CCK | http://uri.interlex.org/ilx_0102124 | http://uri.neuinfo.org/nif/nifstd/nifext_5068 |  
Choline Acetyltransferase | ChAT Choline acetylase | http://uri.interlex.org/base/ilx_0102129 | http://uri.neuinfo.org/nif/nifstd/sao722953401 |  
CNQX | cyanquixaline (6-cyano-7-nitroquinoxaline-2,3-dione) | http://uri.neuinfo.org/nif/nifstd/nlx_14886 |   |  
DAPi | 4,6-diamidino-2-phenylindole |   |   |  
delta opioid receptor | delta DOR | http://uri.neuinfo.org/nif/nifstd/nifext_6921 |   |  
DNQX | 6,7-dinitroquinoxaline-2,3-dione | http://uri.neuinfo.org/nif/nifstd/nlx_76042 |   |  
dopamine | DA dopamin deoxyepinephrine dopamine HCl hydroxyltyramine | http://uri.interlex.org/base/ilx_0103384 | http://purl.obolibrary.org/obo/CHEBI_18243 | https://knowledge-space.org/wiki/CHEBI:18243#dopamine
dopamine transporter | DAT dopamine active transporter | http://uri.interlex.org/base/ilx_0103388 | http://uri.neuinfo.org/nif/nifstd/nlx_mol_20090512, http://purl.obolibrary.org/obo/PR_000015188 | https://knowledge-space.org/wiki/NLXMOL:20090512#dopamine-transporter
dopaminergic antagonist |   |   | https://www.ebi.ac.uk/chebi/searchId.do?chebiId=48561 |  
DPCPX | cyclopentyl-1,3-dipropylxanthine |   | http://id.nlm.nih.gov/mesh/2018/M0255708 |  
Dyn | Dynorphin | http://uri.interlex.org/ilx_0103624 | http://uri.neuinfo.org/nif/nifstd/nifext_5097 |  
Enk | Enkephalin | http://uri.interlex.org/base/ilx_0103826 | http://uri.neuinfo.org/nif/nifstd/nifext_5096 |  
epibatidine |   | http://uri.interlex.org/ilx_0103884 | http://uri.neuinfo.org/nif/nifstd/nlx_chem_20090204 |  
epinephrine | adrenaline AD EPI | http://uri.interlex.org/ilx_0103891 | https://www.drugbank.ca/drugs/DB00668 |  
flumazenil |   | http://uri.interlex.org/base/ilx_0104307 | http://purl.obolibrary.org/obo/CHEBI_5103 |  
Forkhead box protein P2 | FoxP2 |   |   |  
gabazine | SR-95531 | http://uri.interlex.org/base/ilx_0572043 | http://id.nlm.nih.gov/mesh/2018/M0142643, https://ncimeta.nci.nih.gov/ncimbrowser/ConceptReport.jsp?dictionary=NCI%20Metathesaurus&code=C0628385 |  
galanin | GAL | http://uri.interlex.org/base/ilx_0104529 | http://uri.neuinfo.org/nif/nifstd/nifext_5074 | https://knowledge-space.org/wiki/NIFEXT:5074#galanin
ghrelin | GHRL |   | http://uri.neuinfo.org/nif/nifstd/nifext_5076 | https://knowledge-space.org/wiki/NIFEXT:5076#ghrelin
GIRK channel | G Protein-Coupled Inwardly-Rectifying Potassium Channel | http://id.nlm.nih.gov/mesh/2018/M0451133 |   |  
GIRK2 channel | G protein-activated inward rectifier potassium channel 2 |   | http://purl.obolibrary.org/obo/PR_000002003 | https://knowledge-space.org/wiki/PR:000002003#g-protein-activated-inward-rectifier-potassium-channel-2
GLP1 | glucagon-like peptide 1 |   | http://uri.neuinfo.org/nif/nifstd/nifext_5143 | https://knowledge-space.org/wiki/NIFEXT:5143#glucagon-like-peptide-1
GluA1 receptor | AMPA receptor subunit A1, GluA1 AMPA receptor |   |   |  
GluA2 receptor | AMPA receptor subunit A2, GluA2 AMPA receptor |   |   |  
GluA3 receptor | AMPA receptor subunit A3, GluA3 AMPA receptor |   |   |  
glutamate | Glu Glut | http://uri.interlex.org/base/ilx_0104676 | http://uri.neuinfo.org/nif/nifstd/sao1744435799 | https://knowledge-space.org/wiki/SAO:1744435799#glutamate
glutamate transporter 1 | GLT1 |   |   |  
histamine |   | http://uri.interlex.org/base/ilx_0105065 | http://uri.neuinfo.org/nif/nifstd/nifext_5016 | https://knowledge-space.org/wiki/NIFEXT:5016#histamine
insulin | INS |   | http://purl.obolibrary.org/obo/PR_000009054 | https://knowledge-space.org/wiki/PR:000009054#insulin
kappa opioid receptor | kappa KOR | http://uri.neuinfo.org/nif/nifstd/nifext_5660 |   |  
Kv4 channel |   | http://uri.neuinfo.org/nif/nifstd/nifext_2719 |   |  
leptin | LEP OB obese protein obesity factor OBS |   | http://purl.obolibrary.org/obo/PR_000009758 | https://knowledge-space.org/wiki/PR:000009758#leptin-1
Lucifer Yellow | LY | http://uri.interlex.org/base/ilx_0439021 | http://id.nlm.nih.gov/mesh/2018/M0068243, https://ncimeta.nci.nih.gov/ncimbrowser/ConceptReport.jsp?dictionary=NCI%20Metathesaurus&code=C0065228 |  
metabotropic glutamate receptor | mGluR mGluRs GRM Glutamate metabotropic | http://uri.interlex.org/base/ilx_0106829 | http://uri.neuinfo.org/nif/nifstd/nlx_mol_20090503 |  
mGlu1A receptor |   |   |   |  
mGluR1 | metabotropic glutamate receptor 1 GRM1 Glutamate metabotropic receptor 1 metabotropic glutamate 1 | http://uri.interlex.org/ilx_0106891 | http://uri.neuinfo.org/nif/nifstd/nlx_mol_20090504 |  
mGluR2 | metabotropic glutamate receptor 2 GRM2 Glutamate metabotripic receptor 2 Glutamate metabotropic 2 | http://uri.interlex.org/ilx_0106892 | http://uri.neuinfo.org/nif/nifstd/nlx_mol_20090505 |  
mGluR5 | metabotropic glutamate receptor 5  GRM5  Glutamate metabotropic receptor 5 mGlu5 glutamate metabotropic 5 | http://uri.interlex.org/ilx_0106895 | http://uri.neuinfo.org/nif/nifstd/nlx_mol_20090508 |  
MK-801 |   | http://uri.interlex.org/base/ilx_0496139 | http://id.nlm.nih.gov/mesh/2018/M0350546, https://ncimeta.nci.nih.gov/ncimbrowser/ConceptReport.jsp?dictionary=NCI%20Metathesaurus&code=C0813872 |  
mu opioid receptor | µ opioid receptor mu receptor MOR µ-OR µ mu | http://uri.neuinfo.org/nif/nifstd/nifext_6921 |   |  
muscarinic receptor subunit 4 | M4 M4 receptor M4R |   |   |  
muscimol |   | http://id.nlm.nih.gov/mesh/2018/M0014231 | https://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI%3A7035 |  
nicotinic alpha4 beta2 receptor |   |   |   |  
norepinephrine | noradrenaline,  NE, Nad,  NA | http://uri.interlex.org/ilx_0107680 | http://uri.neuinfo.org/nif/nifstd/nifext_5013 | https://knowledge-space.org/wiki/NIFEXT:5013#norepinephrine
NPY | neuropeptide Y |   | http://uri.neuinfo.org/nif/nifstd/nifext_5090, http://purl.obolibrary.org/obo/PR_000011387 | https://knowledge-space.org/wiki/NIFEXT:5090#neuropeptide-y, https://knowledge-space.org/wiki/PR:000011387#neuropeptide-y-1
NPY receptor |   |   | http://uri.neuinfo.org/nif/nifstd/nifext_5809 | https://knowledge-space.org/wiki/NIFEXT:5809#neuropeptide-y-receptor
NTS | neurotensin | http://uri.interlex.org/base/ilx_0107542 | http://uri.neuinfo.org/nif/nifstd/nifext_5092 | https://knowledge-space.org/wiki/NIFEXT:5092#neurotensin
oxotremorine-M |   | http://uri.interlex.org/base/ilx_0522069 | http://id.nlm.nih.gov/mesh/2018/M0126067, https://ncimeta.nci.nih.gov/ncimbrowser/ConceptReport.jsp?dictionary=NCI%20Metathesaurus&code=C0069796 |  
oxytocin | Oxt OXT OT | http://uri.interlex.org/base/ilx_0108336 | http://purl.obolibrary.org/obo/CHEBI_7872 | https://knowledge-space.org/wiki/CHEBI:7872#oxytocin
panAMPA receptor | GluA1-3 receptor |   |   |  
phthalimide-azo-iperoxo | PAI | photo-switchable muscarinic agonist |   |  
picrotoxin | PTX | http://uri.interlex.org/ilx_0108877 |   |  
pirenzepine |   | http://uri.interlex.org/base/ilx_0108914 | http://purl.obolibrary.org/obo/CHEBI_8247 |  
prazosin |   | http://uri.interlex.org/base/ilx_0109181 | http://purl.obolibrary.org/obo/CHEBI_8364 |  
SCH23390 |   |   |   |  
serotonin | 5-hydroxytryptamine 5-HT | http://uri.interlex.org/base/ilx_0110557 | http://uri.neuinfo.org/nif/nifstd/sao711465902 |  
SK channel | small conductance calcium-activated potassium channel |   |   |  
SK2 channel | small conductance calcium-activated potassium channel protein 2 SKCa2, KCNN2 |   | http://purl.obolibrary.org/obo/PR_000000713 |  
substance P | SP | http://uri.interlex.org/base/ilx_0111205 | http://uri.neuinfo.org/nif/nifstd/nifext_5117 | https://knowledge-space.org/wiki/NIFEXT:5117#substance-p
tetrodotoxin | TTX | http://id.nlm.nih.gov/mesh/2018/M0021255 |   |  
UK-14,304 |   | http://uri.interlex.org/base/ilx_0502583 | http://id.nlm.nih.gov/mesh/2018/M0065042, https://ncimeta.nci.nih.gov/ncimbrowser/ConceptReport.jsp?dictionary=NCI%20Metathesaurus&code=C0147760 |  
vasopressin | antidiuretic hormone ADH | http://uri.interlex.org/ilx_0112270 | https://www.drugbank.ca/drugs/DB00067 |  
vesicular GABA transporter | vGAT VGAT |   |   |  
ZM 241385 |   | http://uri.interlex.org/base/ilx_0539235 | http://id.nlm.nih.gov/mesh/2018/M0255708, https://ncimeta.nci.nih.gov/ncimbrowser/ConceptReport.jsp?dictionary=NCI%20Metathesaurus&code=C0384965 |

**Comment by lzehl** [comment]
should we prioritize after available information?
1. all terms with InterLex + preferred onotology
2. all terms with InterLex only
3. all terms with preferred ontology only
4. all terms with no external reference

**Comment by MaaikevS** [comment]
@lzehl That sounds like a sensible prioritisation. 
I can make a start for some of them if you like

**Comment by lzehl** [comment]
@MaaikevS yes please :)
