### ISSUE TITLE
Request to add sulci from UBERON

### ISSUE THREAD

**Issue by AnnaHilverling** [HumanBrainProject/openMINDS_controlledTerms#191]
Hi @lzehl and @UlrikeS91,

would it be possible to pull the sulci and gyri from UBERON and add them as Uberonparcellation entities?

Many thanks!

**Comment by lzehl** [comment]
@AnnaHilverling which ones are missing that you need?

**Comment by AnnaHilverling** [comment]
@lzehl these are the entries I need for a dataset:

- central sulcus: http://purl.obolibrary.org/obo/UBERON_0002916 
- precentral gyrus: http://purl.obolibrary.org/obo/UBERON_0022252
- superior temporal sulcus: http://purl.obolibrary.org/obo/UBERON_0002734

**Comment by UlrikeS91** [comment]
@AnnaHilverling did you mean precentral SULCUS? The link to the UBERON entry is for that one. If you needed precentral gyrus, that one already exists as controlled term which has this UBERON ID: http://purl.obolibrary.org/obo/UBERON_0002703.

**Comment by AnnaHilverling** [comment]
@UlrikeS91 No, I meant the precentral **gyrus**. Then I must have overlooked it. My fault.

**Comment by lzehl** [comment]
should be solved now with #196
