### ISSUE TITLE
Expansion of study target - molecular entity

### ISSUE THREAD

**Issue by AnnaHilverling** [HumanBrainProject/openMINDS_controlledTerms#193]
Hi @lzehl and @UlrikeS91,

I would like to add the below entites as study targets to a dataset:
- 5-HT1B
- 5-HT2A
- 5-HT4
- 5-HTT

The first three are serotonin receptors and the fourth is a serotonin transporter. All four fit under molecular entity. What do you think?

**Comment by lzehl** [comment]
@MaaikevS could you cover those in the next PR for molecular entities?

**Comment by MaaikevS** [comment]
@lzehl Yes, I will include these in the next PR

**Comment by lzehl** [comment]
@MaaikevS perfect :) thank you!! (@AnnaHilverling we'll keep you updated)

**Comment by AnnaHilverling** [comment]
@lzehl and @MaaikevS many thanks :)

**Comment by MaaikevS** [comment]
@lzehl @AnnaHilverling I created the four instances. See PR #197

**Comment by lzehl** [comment]
@AnnaHilverling & @MaaikevS and approved and merged :)
