### ISSUE TITLE
2 new technique proposals 

### ISSUE THREAD

**Issue by AnnaHilverling** [HumanBrainProject/openMINDS_controlledTerms#195]
Hi @skoehnen and @lzehl,

I would like to propose the below registration methods as new technique entities:

- boundary-based registration (BBR) - (see Greve and Fischl et al. 2009, https://doi.org/10.1016/j.neuroimage.2009.06.060)
- combined volume–surface (CVS) registration  - (see Postelnicu et al. 2009, https://dx.doi.org/10.1109%2FTMI.2008.2004426)

Please let me know what you think.
Many thanks and kind regards!

**Comment by lzehl** [comment]
They appear to be both well documented techniques that we can register. @skoehnen would you agree?

**Comment by skoehnen** [comment]
Yes, I agree, we should register those methods.
