### ISSUE TITLE
New techniques (from MRTM model variants)

### ISSUE THREAD

**Issue by AnnaHilverling** [HumanBrainProject/openMINDS_controlledTerms#202]
Hi @skoehnen and @lzehl,

As a result of our discussion, I would like to have the following measurement methods entered as techniques: 
- binding potential measurement
- relative delivery rate measurement
- clearance rate measurement

Many thanks for your help!

**Comment by lzehl** [comment]
@AnnaHilverling the PR is prepared. But I would like to get some expert feedback for those terms.

**Comment by lzehl** [comment]
@AnnaHilverling I've discussed with @tgbugs and we decided to do the following with the MRTM model variants within EBRAINS:
+ register "multilinear regression" as technique
+ register "Multilinear Reference Tissue Model (MRTM)" and variants as keywords
+ register "PET-derived binding potential" etc. as study target

**Comment by tgbugs** [comment]
https://www.pmod.com/files/download/v31/doc/pkin/2316.htm

**Comment by UlrikeS91** [comment]
> @AnnaHilverling I've discussed with @tgbugs and we decided to do the following with the MRTM model variants within EBRAINS:
> 
> * register "multilinear regression" as technique
> * register "Multilinear Reference Tissue Model (MRTM)" and variants as keywords
> * register "PET-derived binding potential" etc. as study target

I've made a PR for the multilinear regression technique. The rest does not need to be handled here. PET-derived binding potential can be added as term suggestion for now. 

@lzehl, I do not now what the status for your draft PR #203 is, but to me it looks like this should be move somewhere else (e.g. MeasuredQuantity). The 3 terms form the PR do not seem suitable techniques.
