### ISSUE TITLE
UBERONparcellation

### ISSUE THREAD

**Issue by szafarnia** [HumanBrainProject/openMINDS_controlledTerms#205]
Dear all,

Could you please add „intraparietal sulcus“ as UBERONparcellations? 
As Information: I found it in the ontology search: https://www.ebi.ac.uk/ols/ontologies/uberon/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FUBERON_0002913

Many thanks in advance.

Best,
Sara

**Comment by UlrikeS91** [comment]
Thanks for adding the ontology link, @szafarnia! I've created the instance. If either @MaaikevS or @lzehl reviews (and merges) it today, you can start using it tomorrow in the KGE ☺️

**Comment by MaaikevS** [comment]
Approved and added!
