### ISSUE TITLE
Aseg Atlas - caudate is missing

### ISSUE THREAD

**Issue by AnnaHilverling** [HumanBrainProject/openMINDS_controlledTerms#208]
Hi @lzehl,

For the Aseg Atlas I miss the region 'Aseg-caudate', respectively cannot find it under parcellation entity.
Would you mind adding it?

Many thanks!

**Comment by lzehl** [comment]
@AnnaHilverling I'll check. this issue should in principle currently go to openMINDS_SANDS (https://github.com/HumanBrainProject/openMINDS_SANDS) where atlases are defined at the moment

**Comment by lzehl** [comment]
@AnnaHilverling PR is made in SANDS and awaiting review. Should be available latest on Friday
