### ISSUE TITLE
Echo-planar imaging

### ISSUE THREAD

**Issue by AnnaHilverling** [HumanBrainProject/openMINDS_controlledTerms#212]
Hi @UlrikeS91, @MaaikevS and @lzehl,

I have the question if echo-planar imaging (EPI) should be listed as a separate technique?
Actually EPI is an MRI pulse sequence and therefore a parameter of MRI. In this form I also found only echo planar pulse sequence via Interlex: https://scicrunch.org/scicrunch/interlex/view/ilx_0103659?searchTerm=echo-planar%20imaging

But how else could EPI be registered? Should it simply be specified as a keyword?

Thanks for your opinions in advance!

**Comment by lzehl** [comment]
@tgbugs we should discuss this one

**Comment by lzehl** [comment]
@AnnaHilverling: based on the discussion with @tgbugs we will register "echo planar pulse sequence" into techniques. 

For curation: register magnetic resonance imaging + the pulse sequence

Other pulse sequences to register:
+ T1 pulse sequence (T
+ T2 pulse sequence (T2 prepared)
+ etc

[look at: https://pubs.rsna.org/doi/10.1148/rg.262055063 and wikipedia MRI sequence page]

**Comment by UlrikeS91** [comment]
What's the status here?

**Comment by lzehl** [comment]
@UlrikeS91 was not done yet. The decision requires a potential clean up of other pulse sequences that were mixed with the acquisition technique (e.g., T1magneticResonanceImaging).

TODO:
1) registration of "echo planar pulse sequence"
2) registration of "T1 pulse sequence"
3) registration of "T2 pulse sequence"
4) removal of "T1-weighted magnetic resonance imaging", cleanup in EBRAINS (MRI + T1 pulse sequence technique)
5) removal of "T2-weighted magnetic resonance imaging", cleanup in EBRAINS (MRI + T1 pulse sequence technique)
6) screening the existing techniques for other cleanups (and correcting them)

**Comment by lzehl** [comment]
Summary of what to define in #262 (@UlrikeS91 for you as support)

term name: **"T1 pulse sequence"**
definition: "In magnetic resonance imaging, a 'T1 pulse sequence' is a contrasting technique that allows the magnetization of the specimen or object to recover (spin-lattice relaxation) before measuring the magnetic resonance signal by changing the repetition time. [adapted from [wikipedia](https://en.wikipedia.org/wiki/Receptive_field)]"
synonyms: "T1 weighted imaging", "T1 weighted magnetic resonance imaging", "T1 weighted MRI", "T1w imaging", "T1w magnetic resonance imaging", "T1w MRI"

term name: **"T2 pulse sequence"**
definition: "In magnetic resonance imaging, a 'T2 pulse sequence'  is a contrasting technique allows the magnetization of the specimen or object to decay (spin-spin relaxation) before measuring the magnetic resonance signal by changing the echo time. [adapted from [wikipedia](https://en.wikipedia.org/wiki/Receptive_field)]"
synonyms: "T2 weighted imaging", "T2 weighted magnetic resonance imaging", "T2 weighted MRI", "T2w imaging", "T2w magnetic resonance imaging", "T2w MRI"

term name: **"echo-planar pulse sequence"**
definition: "In magnetic resonance imaging, a 'echo-planar pulse sequence' is a contrasting technique where each radio frequency field (RF) excitation is followed by a train of gradient echoes with different spatial encoding allowing for very rapid scanning. [adapted from [wikipedia](https://en.wikipedia.org/wiki/Physics_of_magnetic_resonance_imaging#Echo-planar_imaging)]
synonym: "echo-planar imaging"

**Comment by UlrikeS91** [comment]
> Summary of what to define in #262 (@UlrikeS91 for you as support)
> 
> term name: **"T1 pulse sequence"** definition: "In magnetic resonance imaging, a 'T1 pulse sequence' is a contrasting technique that allows the magnetization of the specimen or object to recover (spin-lattice relaxation) before measuring the magnetic resonance signal by changing the repetition time. [adapted from [wikipedia](https://en.wikipedia.org/wiki/Receptive_field)]" synonyms: "T1 weighted imaging", "T1 weighted magnetic resonance imaging", "T1 weighted MRI", "T1w imaging", "T1w magnetic resonance imaging", "T1w MRI"
> 
> term name: **"T2 pulse sequence"** definition: "In magnetic resonance imaging, a 'T2 pulse sequence' is a contrasting technique allows the magnetization of the specimen or object to decay (spin-spin relaxation) before measuring the magnetic resonance signal by changing the echo time. [adapted from [wikipedia](https://en.wikipedia.org/wiki/Receptive_field)]" synonyms: "T2 weighted imaging", "T2 weighted magnetic resonance imaging", "T2 weighted MRI", "T2w imaging", "T2w magnetic resonance imaging", "T2w MRI"
> 
> term name: **"echo-planar pulse sequence"** definition: "In magnetic resonance imaging, a 'echo-planar pulse sequence' is a contrasting technique where each radio frequency field (RF) excitation is followed by a train of gradient echoes with different spatial encoding allowing for very rapid scanning. [adapted from [wikipedia](https://en.wikipedia.org/wiki/Physics_of_magnetic_resonance_imaging#Echo-planar_imaging)] synonym: "echo-planar imaging"

- removing "technique" is fine.
- definitions sound good but your hyperlink for T1 and T2 point to the Wikipedia entry for "receptive field"; I couldn't find one specifically for those sequences just the overarching one for MRI sequences (https://en.wikipedia.org/wiki/MRI_sequence) which has some descriptions but your definition does not seem to be adapted from that entry, so remove it?
- I'm unsure about the synonyms, but probably only because I'm not an expert in the fields; to me, these seem like related synonyms not exact synonyms...

**Comment by lzehl** [comment]
@UlrikeS91 its the overarching one you found... sorry for the copy/paste error
the synonyms are a collection of what is typically used in the community (across different sources); the decision to establish T1 and T2 (etc.) really as pulse sequences is often shortened in the community to "imaging" variant

**Comment by UlrikeS91** [comment]
Ok, thanks for the clarifications! I'll update my draft and make it a proper PR 🙂
