### ISSUE TITLE
CCEP (cortico-cortical evoked potential) mapping

### ISSUE THREAD

**Issue by lzehl** [HumanBrainProject/openMINDS_controlledTerms#214]
CCEP mapping is a relatively novel in vivo brain mapping technique, utilizing low frequency stimulation, in patients undergoing invasive monitoring for refractory epilepsy (Matsumoto et al., 2004). CCEP mapping produces evoked effective connectivity data.

**Comment by lzehl** [comment]
I suggest we add this to our Technique terminology. FYI @tgbugs & @MaaikevS

**Comment by UlrikeS91** [comment]
Just to clarify: You want to add it as an analysis technique, right? I looked at some papers that used this mapping and the experimental technique in most cases would be "electrocorticogram" (ECoG) and an electrical stimulation (of distinct areas). Then the causal relation between brain regions following the stimulation is evaluated, meaning did the stimulation in area A trigger an electrical response in area B of a certain strength, timing and type. "CCEPs in human cortex generally consist of an early sharp response (10–50 ms poststimulation) and a later slow-wave (50–250 ms).", according to [Keller et al. (2014)](https://www.jneurosci.org/content/34/27/9152). 

So, a definition for the technique could be something like:
"Cortico-cortical evoked potential (CCEP) mapping is an analysis technique used to identify the pattern of CCEPs (electrical response with specific strength, timing and shape) of multiple units within a nervous system following direct electrical stimulation of another unit."

Description could be:
"Cortico-cortical evoked potentials are distinct electrical responses in specific units of a nervous system following direct electrical stimulation of another unit in the same system. For example, CCEPs in human cortex generally consist of an early sharp response (10–50 ms poststimulation) and a later slow-wave (50–250 ms) [[Keller et al. (2014)]](https://www.jneurosci.org/content/34/27/9152). By mapping the response patterns, the effective connectivity (= causal interactions) between those units can be determined. The analysis of the network topology typically involves graph theory measures."

**Comment by lzehl** [comment]
@UlrikeS91 thanks for you summary. we need to be careful here to distinguish between the recorded signal, meaning the cortico-cortical evoked potentials, and the stimulation / analysis technique that uses repeated stimulations to evoke multiple CCEPs across the brain to determine effective connectivity. So we need it "twice": as study target we need cortico-cortical evoked potential as evoked neuronal signal, and as technique we need CCEP mapping.

**Comment by UlrikeS91** [comment]
Conclusion from offline discussion:
1. Add CCEP as "experimental measurement", related to https://github.com/HumanBrainProject/openMINDS_controlledTerms/issues/151. FYI @MaaikevS, this is also added as a TermSuggestion already in the KG with the following definition: "A 'cortico-cortical evoked potential' is a an evoked neuronal population response to a brief electrical pulse used to mimic the physiological propagation of signals. The first component of the cortico-cortical evoked potentials is believed to reflect direct connectivity with the stimulated region. [adapted from [Trebaul et al. 2016](http://dx.doi.org/10.1016/j.jneumeth.2016.03.002)]"

2. Add "cortico-cortical evoked potential mapping" as "technique" (with synonym "CCEP mapping"). Suggested definition: "Cortico-cortical evoked potential (CCEP) mapping is used to identify the effective connectivity between distinct neuronal populations based on multiple CCEP measurements across (parts of) the brain in response to direct electrical stimulation (typically at various locations)."
