### ISSUE TITLE
ensemble bagging machine learning

### ISSUE THREAD

**Issue by lzehl** [HumanBrainProject/openMINDS_controlledTerms#215]
suggestion for new Technique. @skoehnen could you take this over? I think you can write the better definition....

**Comment by skoehnen** [comment]
@lzehl I will take a look.

**Comment by UlrikeS91** [comment]
At least one of the PRs seems to be ready for another round of review. @lzehl, could you please have a look?

**Comment by UlrikeS91** [comment]
Will be handled in PR https://github.com/openMetadataInitiative/openMINDS_instances/pull/79. I'm closing the issue here.
