### ISSUE TITLE
New subjectAttribute

### ISSUE THREAD

**Issue by MaaikevS** [HumanBrainProject/openMINDS_controlledTerms#222]
Hi @UlrikeS91 @lzehl,

Could we add a subject attribute for "injected" or something similar (e.g. "treated"). This is not for drug treatment, but mainly for an injection of a tracer for example. I know we could make these things clear when adding protocols (which I will add anyway), but I think it would be beneficial to also be able to "tag" subjects with an attribute that describes that state.

Any thoughts of this?

**Comment by UlrikeS91** [comment]
We have "untreated" and "drugged" (see PR #175). I see how "drugged" won't work in this case, but I guess we could add "treated" as well. This should cover most other cases and doesn't imply that drugs/medicine was used. @lzehl what do you think?

**Comment by MaaikevS** [comment]
Thanks for the quick response. I agree and I would be happy with "treated" for now

**Comment by MaaikevS** [comment]
Subject attribute "treated" has now been added. Thanks @UlrikeS91
