### ISSUE TITLE
Request to add more Uberonparcellations

### ISSUE THREAD

**Issue by AnnaHilverling** [HumanBrainProject/openMINDS_controlledTerms#223]
Hi all,
I would like to ask if the following study target can be added as Uberonparcellation:
- auditory cortex (http://purl.obolibrary.org/obo/UBERON_0001393)

Then I have a question about the study target "medial temporal lobe". Medial temporal lobe (MTL) does not exist in the Uberonparcellation. According to the literature, the following cortex structures belong to the MTL, all of which can be found in the Uberonparcellation (and is already registered in KGE):
- perirhinal cortex (http://purl.obolibrary.org/obo/UBERON_0006083)
- entorhinal cortex (http://purl.obolibrary.org/obo/UBERON_0002728)
- parahippocampal gyrus (http://purl.obolibrary.org/obo/UBERON_0002973)

Should I better choose the existing Uberonparcellations above or register "medial temporal lobe" as a custom anatomical entity?

Many thanks for your opinion on this in advance!

**Comment by UlrikeS91** [comment]
Thanks for the request, @AnnaHilverling! 

Auditory cortex should be added, I will makke a PR for it (and others, depending on the conlusion for the MTL request).

Medial temporal lobe is a tricky one. I found e.g. this article, https://www.frontiersin.org/articles/10.3389/fnana.2018.00098/full, that defines the MTL regions in Figure 2 to be many more than the 3 that you mentioned. This also fits with my personal definition fo the MTL regions.  

I think the simplest approach is to handle this case-by-case. What would be your specific use case? 

I can see 3 different options:
1. If the researcher has studied specific MTL regions, I would probably add the specific regions as UBERON terms. "medial temporal lobe" could then be a keyword instead. 
2. If the researcher does not want to specify the regions of interest, then MTL could be entered as a custom anatomical entity. 
3. if the researcher wants MTL as a specific study target, then we can add the custom anatomical entity. If they additionally would like to highlight some of the MTL regions explicitly, you could add those as UBERON terms to the study target.

**Comment by AnnaHilverling** [comment]
Hi @UlrikeS91, thanks for your quick response!

Concerning the MTL regions. Yes, you are right, the hippocampal regions are also included in the MTL, but since the researcher had already explicitly named this region as a study target, I did not consider to mention it here. I should have mentioned that I had already added "hippocampal formation" as a study target  🙃 🙂 
I cannot find the "temporopolar cortex" in the Uberon parcellation. This would then also have to be added via the custom anatomical entity. 
But let me ask the researcher about the options first. Then I will get back to you. 
Thank you!

**Comment by AnnaHilverling** [comment]
Hi @UlrikeS91 ,

I received feedback from the data provider concerning the registration of areas.

The data provider would like to have registered the following terms:

- Hippocampus 
- medial frontal lobe 
- auditory cortex (http://purl.obolibrary.org/obo/UBERON_0001393)
- medial temporal lobe 
- medial parietal lobe 

Since Hippocampus, MFL, MTL and MPL cannot be found in the Uberon parcellation, can this be registered as custom anatomical entity? 

Best, Anna

**Comment by AnnaHilverling** [comment]
Hi @UlrikeS91 ,

Just as a heads-up. I am linking @szafarnia here as she will take over the curation of the associated dataset. 

Best, Anna

**Comment by UlrikeS91** [comment]
Hi @szafarnia,

Sorry about the very late response. This must have slipped through the cracks...

As Anna summarized correctly, MFL, MTL and MPL don't exist in the UBERON terminology, so these need to be added as custom anatomical entities instead. 

Both hippocampus and auditory cortex don't exist as instances in our openMINDS terminology yet. So, I will update the draft #266 and we get them integrated asap.

**Comment by UlrikeS91** [comment]
PS: I'm closing the issue now, since the PR is ready and will be merged (maybe with some minor adjustments, but eventually).

**Comment by UlrikeS91** [comment]
Quick update: The UBERON term for "hippocampus" is actually called "Ammon's horn", so please use that one ☺️

**Comment by szafarnia** [comment]
Thanks a lot for info.
