### ISSUE TITLE
new technique: retinotopic mapping

### ISSUE THREAD

**Issue by szafarnia** [HumanBrainProject/openMINDS_controlledTerms#227]
Dear all,

Could you please add "retinotopic mapping" as new technique to KG?

Many thanks in advance.

Best,
Sara

**Comment by lzehl** [comment]
@tgbugs @UlrikeS91 @MaaikevS could we discuss this in the ontology meeting? I would argue that this fits since we also support receptive field mapping.

**Comment by tgbugs** [comment]
The two techniques are separate. Most simply, receptive fields can apply to more than the visual system. Receptive field mapping is usually to single cells where as retinotopic mapping is whole populations/swaths of cortex. See https://doi.org/10.1016/j.neuron.2016.07.015 for an example of a transition between the two levels.
