### ISSUE TITLE
new techniques: filtering 

### ISSUE THREAD

**Issue by lzehl** [HumanBrainProject/openMINDS_controlledTerms#237]
filtering
"Filtering is a class of signal processing, the defining feature of filters being the complete or partial suppression of some aspect of the signal. [[wikipedia](https://en.wikipedia.org/wiki/Filter_(signal_processing))"

also:
high-pass filtering
low-pass filtering
band-pass filtering

**Comment by apdavison** [comment]
Maybe call this "signal filtering" to avoid confusion with physical/chemical filtering (e.g. removing impurities from a substance, removing certain frequencies or polarizations from a light beam)?

**Comment by lzehl** [comment]
@apdavison yes. good point

**Comment by tgbugs** [comment]
We have `signal filtering technique` http://uri.interlex.org/base/ilx_0739623 and `signal processing technique` http://uri.interlex.org/base/ilx_0739633 .

**Comment by lzehl** [comment]
note: on the long run we will need to add more specific filtering and signal processing techniques
