### ISSUE TITLE
potential technique: fluorodeoxyglucose-positron emission tomography

### ISSUE THREAD

**Issue by lzehl** [HumanBrainProject/openMINDS_controlledTerms#246]
FDG-PET

@tgbugs should we capture the different PET types?

**Comment by tgbugs** [comment]
Yes we should. Not entirely sure how to model this. It seems that it is probably similar to how we model RNA-seq where there is a part of the technique that involves putting someone in the scanner. Only the contrast agent changes. I think we add contrast agent administration technique and then if we wanted to create a composite technique it becomes PET plus a parametrized contrast agent administration.

**Comment by lzehl** [comment]
TODO:
- add technique "contrast agent administration"
