### ISSUE TITLE
new technique: ELISA (Enzyme-linked Immunosorbent Assay)

### ISSUE THREAD

**Issue by szafarnia** [HumanBrainProject/openMINDS_controlledTerms#271]
Dear all,

Could you please add „ELISA (Enzyme-linked Immunosorbent Assay)” as a technique to the KG?

Many thanks in advance.

Best,
Sara

**Comment by lzehl** [comment]
@tgbugs and @UlrikeS91 what is our position on assays? do we register them (for now) under techniques if they are well established?

**Comment by UlrikeS91** [comment]
ELISA is definitely well established. I think it should be fine to add this one as a technique even though it may not fall into this category in the classical sense since it is more like a protocol.
