### ISSUE TITLE
new techniques: diagnose checklists ???

### ISSUE THREAD

**Issue by lzehl** [HumanBrainProject/openMINDS_controlledTerms#274]
examples: DSM-V criteria, Clinical Global Impression (CGI-S) Autism Treatment Evaluation Checklist (ATEC), the Autism Diagnostic Interview-Revised (ADI-R), the Autism Behavior Checklist (ABC) and the Childhood Autism Rating Scale (CARS)

I think we already have some checklists under techniques...

@tgbugs @UlrikeS91 what do you think???

**Comment by UlrikeS91** [comment]
This feels more like (behavioural) protocols to me. The technique would be something like "criteria testing" (please do not take that term to seriously 😆).

**Comment by lzehl** [comment]
@UlrikeS91 thanks yes that's were we can put them best.
