### ISSUE TITLE
new techniques: statistical tests

### ISSUE THREAD

**Issue by lzehl** [HumanBrainProject/openMINDS_controlledTerms#275]
Shapiro-Wilk normality test
Independent-Samples Mann-Whitney U Test
Spearman’s correlation test
Grubbs' test
etc. 

@tgbugs & @UlrikeS91 what do you think?

@apdavison or should these go into the new DifferenceMeasure?

**Comment by apdavison** [comment]
@lzehl no, DifferenceMeasure represents the output from (a subset of) statistical tests

**Comment by lzehl** [comment]
@apdavison thank you for the clarification. I'll create a PR then.

**Comment by UlrikeS91** [comment]
I think we already added some statistical tests, so I don't see any reason to exclude these now. We may want to discuss if we want to split them out at some point but for now, I would suggest to just add them.
