### ISSUE TITLE
Inconsistency in definition and description property of UBERONParcellation instances

### ISSUE THREAD

**Issue by ehennestad** [HumanBrainProject/openMINDS_controlledTerms#288]
There appear to be some inconsistencies with regards to what goes into the definition and the description properties of UBERONParcellation instances.  As per issue https://github.com/HumanBrainProject/openMINDS_controlledTerms/issues/278#issue-1358459130: 

>   The definition should always describe the anatomical organization of the term (phrase needs of course to be adapted a bit depending on the term): "'TERM' is a XXX of YYY. It is part of the ZZZ." The description just takes whatever is additionally provided through the UBERON ontology or the InterLex entry

the definition property should be according to the formula ‘TERM’ is a XXX of YYY. It is part of the ZZZ.

**Examples where this formula goes in the definition:**

https://github.com/HumanBrainProject/openMINDS_controlledTerms/blob/e794a396d1bc6cfeaea58e3239bce6bfdf2a670f/instances/UBERONParcellation/vagalNerveFiberBundle.jsonld#L7-L8
https://github.com/HumanBrainProject/openMINDS_controlledTerms/blob/e794a396d1bc6cfeaea58e3239bce6bfdf2a670f/instances/UBERONParcellation/basolateralAmygdaloidNuclearComplex.jsonld#L7-L8
https://github.com/HumanBrainProject/openMINDS_controlledTerms/blob/e794a396d1bc6cfeaea58e3239bce6bfdf2a670f/instances/UBERONParcellation/CA2StratumRadiatum.jsonld#L7-L8

**Examples where this formula goes in the description:**

https://github.com/HumanBrainProject/openMINDS_controlledTerms/blob/e794a396d1bc6cfeaea58e3239bce6bfdf2a670f/instances/UBERONParcellation/valvulaCerebelli.jsonld#L7-L8
https://github.com/HumanBrainProject/openMINDS_controlledTerms/blob/e794a396d1bc6cfeaea58e3239bce6bfdf2a670f/instances/UBERONParcellation/vasculatureOfBrain.jsonld#L7-L8
https://github.com/HumanBrainProject/openMINDS_controlledTerms/blob/e794a396d1bc6cfeaea58e3239bce6bfdf2a670f/instances/UBERONParcellation/arthropodOpticLobe.jsonld#L7-L8

**Comment by UlrikeS91** [comment]
@ehennestad, thanks for raising the issue! I assume that this is a historical issue. If I remember correctly, we only came up with the naming convention after some first instances had been added the other way around (or without any definition/description). 

You are very welcome to do a clean-up and switch the definitions and descriptions 🙂
