### ISSUE TITLE
new technique: slice timing correction (STC)

### ISSUE THREAD

**Issue by szafarnia** [HumanBrainProject/openMINDS_controlledTerms#294]
Dear all,

can "slice timing correction (STC)" be added as new technique?
Here short description that I found: slice timing correction (STC) is the preprocessing step applied to correct for these slice-dependent delays, achieved by shifting the time series of each slice to temporally align all slices to a reference time-point.

Best,
Sara

**Comment by lzehl** [comment]
@szafarnia thanks for raising the issue and making the suggestion. We can integrate this term.
