### ISSUE TITLE
new technique: temporal filtering 

### ISSUE THREAD

**Issue by szafarnia** [HumanBrainProject/openMINDS_controlledTerms#295]
Dear all,

Can "temporal filtering " be added as new technique?
Here short description that I found: Temporal filtering aims to remove or attenuate frequencies within the raw signal, that are not of interest. This can substantially improve the SNR. The tricky thing is to decide which frequencies are of interest and which are noise.

Best,
Sara

**Comment by lzehl** [comment]
@szafarnia please use at the moment "signal filtering technique"

**Comment by szafarnia** [comment]
@lzehl Could „**temporal filtering**“ also be added as new technique? The data provider of the dataset “[Investigating Temporal Predictions Using Virtual Environments at 3T fMRI (v1)](mailto:https://search.kg.ebrains.eu/instances/b884fb7e-c222-4c29-aa5d-f89f014f7d44?group=curated)” is not happy with the technique “signal filtering technique”. She prefers to add „temporal filtering“ as technique to her dataset because this is an important point for the type of analysis they have applied.

**Comment by lzehl** [comment]
@szafarnia please add this for now as keyword. I will bring this up as a discussion again

**Comment by lzehl** [comment]
@tgbugs @ehennestad please have a look at this

**Comment by tgbugs** [comment]
I think you could make this a subclass of signal processing because temporal filtering is a distinct technique since it seems to be a specific algorithm that is distinct.
