### ISSUE TITLE
New 'molecularEntity' suggestions

### ISSUE THREAD

**Issue by archgogo** [HumanBrainProject/openMINDS_controlledTerms#300]
We forward these term suggestions that EBRAINS received from data providers:
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/archanag/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/archanag/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link=blue vlink=blue>

name | suggestedTerminology | interlex ID | Notes | definition
-- | -- | -- | -- | --
panAMPA receptor | molecularEntity |   |   |  
noradrenergic system | molecularEntity | http://uri.interlex.org/base/ilx_0107679 |   | any molecule, protein, cell, tissue or organ that is related   to norepinephrine (also known as noradrenaline).
glutamate system | molecularEntity | http://uri.interlex.org/base/ilx_0104682 |   |  
serotonergic system | molecularEntity | http://uri.interlex.org/base/ilx_0110555 |   |  
adenosine receptor system | molecularEntity |   |   |  
cholinergic system | molecularEntity (from interlex) | http://uri.interlex.org/base/ilx_0102133 |   |  
GABAergic system | molecularEntity (from interlex) | http://uri.interlex.org/base/ilx_0104506 |   |  
mGlu5 receptor | molecularEntity (from interlex) | http://uri.interlex.org/base/ilx_0106895 |   | Group I metabotropic glutamate receptor, positively coupled to   phospholipid metabolism.

</body>

</html>

**Comment by UlrikeS91** [comment]
My feedback to the list:

name | add as molecularEntity? | reason
-- | -- | -- 
panAMPA receptor | yes | but hear with @lzehl about what exact term to add; we had a discussion about the names in #259
noradrenergic system | no | add under the new terminology "BodySystem", see #292; FYI @ehennestad
glutamate system | no | see above
serotonergic system | no | see above
adenosine receptor system | no | see above 
cholinergic system | no | see above
GABAergic system | no | see above
mGlu5 receptor | yes | similar to existing term "metabotropic glutamate receptor 1"

**Comment by lzehl** [comment]
@archgogo thank you for sorting through this and making the issue. 

I agree with @UlrikeS91 that we should group all neurotransmitter systems into body systems.

mGlu5 receptor already exists (https://github.com/HumanBrainProject/openMINDS_controlledTerms/blob/v1/instances/molecularEntity/metabotropicGlutamateReceptor5.jsonld)

For the panAMPA receptor I need to do more research, but as far as I can see this is a synonym for the AMPA receptor which already exists (https://github.com/HumanBrainProject/openMINDS_controlledTerms/blob/v1/instances/molecularEntity/AMPAReceptor.jsonld).

**Comment by archgogo** [comment]
@lzehl, pull requests in 'organismSystem' for 'noradrenergic system', 'glutamatergic system', 'serotonergic system', 'cholinergic system', and 'gabaergic system'. 
Couldn't find any information on 'panAMPA receptor' and 'adenosine receptor system', so no pull requests are made for these

**Comment by lzehl** [comment]
@archgogo thank you for the PRs they should be all merged now!
