### ISSUE TITLE
New 'subcellularEntity' suggestions

### ISSUE THREAD

**Issue by archgogo** [HumanBrainProject/openMINDS_controlledTerms#301]
We forward these term suggestions that EBRAINS received from data providers:
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/archanag/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/archanag/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link=blue vlink=blue>

name | suggestedTerminology | interlex ID | Notes | definition
-- | -- | -- | -- | --
nerve fibers | subcellularEntity | http://uri.interlex.org/base/ilx_0485634 |   | Slender processes of NEURONS,   including the AXONS and their glial envelopes (MYELIN SHEATH). Nerve fibers   conduct nerve impulses to and from the CENTRAL NERVOUS SYSTEM.
axon terminal | subcellularEntity (from interlex) | http://uri.interlex.org/base/ilx_0101049 |   |  

</body>

</html>

**Comment by UlrikeS91** [comment]
Yes to both terms, you can prepare a pull request for those. I can help you offline with this 🙂
