### ISSUE TITLE
New technique suggestion: movement tracking

### ISSUE THREAD

**Issue by spieschnik** [HumanBrainProject/openMINDS_controlledTerms#312]
Hi,

Could you add "movement tracking" as a technique?

**Comment by lzehl** [comment]
@UlrikeS91 we can make "motion tracking" as a synonym to "movement tracking"

**Comment by UlrikeS91** [comment]
> @UlrikeS91 we can make "motion tracking" as a synonym to "movement tracking"

Motion tracking is already a synonym for the term (and the term was also already merged) 🙂
