### ISSUE TITLE
new technique: abstract image visual stimulation

### ISSUE THREAD

**Issue by szafarnia** [HumanBrainProject/openMINDS_controlledTerms#316]
Hi,
Could you please add "abstract image visual stimulation" as a technique?

**Comment by lzehl** [comment]
Yes we can add this for now. This would be the counter part to "natural image visual stimulation".

Definition suggestion: "In an 'abstract image visual stimulation' a subject is visually stimulated with a static image that does not show a natural scene but displays only reduced (abstract) information and forms (e.g., a red symbol on white background)."
(other suggestions for the definition are highly welcome)

**Comment by lzehl** [comment]
@szafarnia this term was added and should be available in EBRAINS by now
