### ISSUE TITLE
new technique: random dot motion stimulation 

### ISSUE THREAD

**Issue by szafarnia** [HumanBrainProject/openMINDS_controlledTerms#317]
Hi,
Could you please add "random dot motion stimulation" as a technique?

**Comment by lzehl** [comment]
Yes we can add this for now. 

Suggested definition: "In a 'random dot motion stimulation' a random dots are simulated in an image and re-positioned at a new random location with each video frame (Newsome & Paré, 1988)."

**Comment by tgbugs** [comment]
Maybe add synonym `random dot visual stimulation` and `random dot visual stimulation technique`?

**Comment by lzehl** [comment]
@szafarnia this term was added and should be also available by now in EBRAINS
