### ISSUE TITLE
New 'Uberonparcellation' suggestions

### ISSUE THREAD

**Issue by spieschnik** [HumanBrainProject/openMINDS_controlledTerms#318]
Hi,

Can we add entorhinal cortex layer 5 (http://purl.obolibrary.org/obo/UBERON_0022325) and entorhinal cortex layer 6 (http://purl.obolibrary.org/obo/UBERON_0022329)?

**Comment by UlrikeS91** [comment]
Hi @spieschnik,

Yes, we can add those - very clear cases. I would actually like you to make the pull request yourself. I can show you how to do it offline 🙂
