### ISSUE TITLE
datasetType terminology update 

### ISSUE THREAD

**Issue by UlrikeS91** [HumanBrainProject/openMINDS_controlledTerms#32]
Change to:
- rawData
- derivedData
- experimentalData
- simulatedData
- GDPRSensitiveData

Idea is to combine the different term to describe the content of the dataset. For example, human non-aggregated data would need the terms `derivedData` + `experimentalData` + `GDPRSensitiveData`.

**Comment by lzehl** [comment]
this one was solve with #33 and changes related to #37
