### ISSUE TITLE
technique request: genome-wide association study (GWA study, or GWAS)

### ISSUE THREAD

**Issue by lzehl** [HumanBrainProject/openMINDS_controlledTerms#330]
https://en.wikipedia.org/wiki/Genome-wide_association_study

@tgbugs and @UlrikeS91 I think we can add this as technique. What is your opinion ?

**Comment by UlrikeS91** [comment]
I've merged the PR. I think this is suitable as a technique (at least for now since we are still adding analysis techniques).
