### ISSUE TITLE
disease request: atrophy ? 

### ISSUE THREAD

**Issue by lzehl** [HumanBrainProject/openMINDS_controlledTerms#331]
not sure if this should be categorized as disease, but since we collect under that terminology fuzzy terms (also syndroms) I think it would be the place for now.

https://en.wikipedia.org/wiki/Atrophy

**Comment by UlrikeS91** [comment]
Yes, this is suitable for the disease terminology, and the more specific one even more so. Would we want to add this in some way as a diseaseModel as well? This was at least our logic so far for all terms that were added either for disease or disease model.

**Comment by lzehl** [comment]
@UlrikeS91 if you know a respective disease model directly yes. I assume there would potentially be multiple ones...

**Comment by UlrikeS91** [comment]
Yes, there are for sure multiple specific ones, but I was thinking of an overarching one as well. Something like "cerebralAtrophyModel" (similar to ["strokeModel"](https://github.com/HumanBrainProject/openMINDS_controlledTerms/blob/v1/instances/diseaseModel/strokeModel.jsonld)).

A definition could aslo be close to what the stroke model has. Stroke model definition: "An animal or cell displaying all or some of the pathological processes that are observed during stroke in humans or animals."
E.g.: "An animal or cell displaying all or some of the pathological processes that are observed for cerebral atrophy in humans or animals."

**Comment by lzehl** [comment]
@UlrikeS91 sounds good to me if there are disease models for this.

**Comment by lzehl** [comment]
I'm closing this issue for now. We can add the disease models for atrophy when they are requested (or when we have time defining them)
