### ISSUE TITLE
technique request: gradient echo (GRE) pulse sequence

### ISSUE THREAD

**Issue by lzehl** [HumanBrainProject/openMINDS_controlledTerms#332]
not sure if one needs to create t1w gre and t2w gre or if the combination t1w or t2w + gre is sufficient.

@tgbugs and @UlrikeS91 please advise

**Comment by UlrikeS91** [comment]
No idea, I cannot help with this. @tgbugs hopefully has an opinion?

**Comment by UlrikeS91** [comment]
This is solved with PR #372.
