### ISSUE TITLE
technique request: sublaminal complex visual stimulation

### ISSUE THREAD

**Issue by lzehl** [HumanBrainProject/openMINDS_controlledTerms#333]
the term came up as "sublaminal complex visual stimuli (faces and bodies)"

@tgbugs how should we register this?

**Comment by lzehl** [comment]
I think this should be registered as "subliminal visual stimulation".

**Comment by tgbugs** [comment]
I think `subliminal visual stimulation technique` works, possibly with a parent class `subliminal stimulation technique` which would be sensory modality agnostic, though it is not subliminal to the modality, only to the ability to generate a verbal report of some higher order feature in the stimulus ....

**Comment by lzehl** [comment]
PR should be made for: 
+ subliminal visual stimulation technique
+ subliminal stimulation technique

**Comment by aeidi89** [comment]
@spieschnik and I will make PRs for these

**Comment by aeidi89** [comment]
@tgbugs controlled_Terms for 'subliminal visual stimulation' and 'subliminal stimulation' have been created.
