### ISSUE TITLE
Request for DCM registered as a technique

### ISSUE THREAD

**Issue by maciej-jedynak** [HumanBrainProject/openMINDS_controlledTerms#340]
Metadata for the F-TRACT dataset will need a Dynamic Causal Modeling (DCM) to be registered as a Technique.

References (first, a general one, then in the context of EEG):
Friston, K.J., Harrison, L., Penny, W., 2003. Dynamic causal modelling. Neuroimage 19, 1273-1302. 
David O, Kiebel SJ, Harrison LM, Mattout J, Kilner JM, Friston KJ. Dynamic causal modeling ofevoked responses in EEG and MEG. Neuroimage. 2006;30(4):1255–1272.

**Comment by UlrikeS91** [comment]
Closing it, will be handled here: https://github.com/openMetadataInitiative/openMINDS_instances/pull/81
