### ISSUE TITLE
remove GitHub and GitLab instance from FileRepositoryType

### ISSUE THREAD

**Issue by lzehl** [HumanBrainProject/openMINDS_controlledTerms#346]
https://github.com/HumanBrainProject/openMINDS_controlledTerms/tree/v1/instances/fileRepositoryType

Remove "GitHub" and "GitLab" instance and add instead "git" (which is the type of the version control system that both web services are using). Add also "git-annex" as instance.

**Comment by skoehnen** [comment]
I will take a look.

**Comment by skoehnen** [comment]
Someone please check if it is correct.

**Comment by lzehl** [comment]
@skoehnen could you also add git-annex to the list? (I assume that this makes sense) and double check the definitions of the other terms for file repo types? (so that they really give a hint on the peculiarities of the repo type?)

**Comment by lzehl** [comment]
I will close this one now and create a new issue for missing FileRepoTypes
