### ISSUE TITLE
Add ontology identifiers for modalties.

### ISSUE THREAD

**Issue by tgbugs** [HumanBrainProject/openMINDS_controlledTerms#35]
Modalities have InterLex ids
https://github.com/HumanBrainProject/openMINDS_controlledTerms/tree/v1/terminologies/modality
are in https://github.com/SciCrunch/NIF-Ontology/blob/master/ttl/generated/modality-ILX-mapping.ttl and
https://github.com/SciCrunch/NIF-Ontology/blob/methods/ttl/modality.ttl.

**Comment by UlrikeS91** [comment]
Thanks, @tgbugs. I'll add them tomorrow.
