### ISSUE TITLE
adding a super class for epidermal electrophysiology techniques

### ISSUE THREAD

**Issue by lzehl** [HumanBrainProject/openMINDS_controlledTerms#352]
@tgbugs & @UlrikeS91 I need your input here.

There are a bunch of different epidermal electrophysiology te)chniques of which some received a clear term (e.g. electrocardiography) and some not (e.g. measurement of electrodermal activity). For the latter it is typically just said that electrodes were placed on the skin of a subject...

Could we discuss a proper technique term for the latter case?

This issue came up in the PR #351 by @eapapp

**Comment by UlrikeS91** [comment]
I thought that we actually discussed this issue before for some reason. I think it makes sense to add a superclass. I think "epidermal electrophysiology technique" would be suitable.

**Comment by lzehl** [comment]
top. I will add it asap

**Comment by lzehl** [comment]
question remains if we find a proper term for the case "electrodes were placed on the skin of a subject"

**Comment by lzehl** [comment]
vs. the proper techniques EKG, EEG, etc which are also "epidermal electrophysiology technique"

**Comment by UlrikeS91** [comment]
We don't have any techniques (yet?) that represent the act of placing electrodes (or similar devices). I'm not sure we would need them, though. 
The placement of the electrode on the skin is a requirement to be able to do epidermal ephys. Some goes for other placements, like inserting an electrode into a cell before doing intracellular injections or the insertion of a biopsy needle into the liver to do a liver biopsy. 
I know that this is a bit oversimplified, but I don't think we need to cover the placement unless that is something extremely special or is the only act (as in "placing the electrode but then not doing anything with it").
