### ISSUE TITLE
adding 'healthy' to SubjectAttribute

### ISSUE THREAD

**Issue by lzehl** [HumanBrainProject/openMINDS_controlledTerms#353]
@UlrikeS91 I thought it might be useful to add 'healthy' as term to the SubjectAttribute terminology for the option to highlight that a subject/subject group is considered (was selected because it is) healthy. Do you agree?

**Comment by UlrikeS91** [comment]
I see your point but I'm not sure "healthy" is a good term. I think it is too ambiguous. A person with a disorder, can be healthy in the sense that either their disorder does not make them very sick in general or is otherwise healthy (except for having the disorder). But it could also mean that only persons without any kind of deviation from "normal" pathology is considered healthy.
Same goes for the opposite "sick" which would be a term to add to the terminology if "healthy" was added. 

It may not be a huge problem if we have a very strict definition but maybe we could consider alternative terms?

**Comment by UlrikeS91** [comment]
Addition: The closest term I could find in InterLex is "healthy volunteers" (http://uri.interlex.org/base/ilx_0491211). This is pretty much what you are looking for, correct?

It is defined as: "Persons with no known significant health problems who are recruited to participate in research to test a new drug, device, or intervention as controls for a patient group."
 
This is actually included in the term "control". Our definition for control is bad and only partially covers the true meaning, though. Better suitable would be: "An organism that acts as "control" is used as a standard of comparison to test the effect of one (or few) variable factors." The description could then contain: "An organism can act as a "control" when it is either as identical to another organism as possible and the two groups are treated in different ways (to test the effect of the different treatments) or by being different and treated the same way (to test the effect of the treatment on different pathologies)." (definitely room for improvement on the description...)

So, a "healthy volunteer" would be a subgroup of controls where the same treatment is given to a patient group and a healthy group (variable factor here is the health condition - one group with no known significant health problems and the other with a specific health problem).

**Comment by lzehl** [comment]
@UlrikeS91 I do not like that healthy volunteers are only regarded as a subgroup of control. They can be not at all controls but just the main subjects of a research study which should be only conducted on healthy subjects. And controls also do not have to be 'healthy' (as you already pointed out) they just need to have the opposite test variable of interest in comparison to the patient group. 

So in my opinion we can make use of the term 'healthy volunteer' but I would generalize the definition a bit more:
"Persons with no known significant health problems who are recruited to participate in research study."
 
What do you think?

**Comment by lzehl** [comment]
I think we need to discuss this more. 'healthy volunteers' is probably not a good idea as a subject attribute since it would only fit to humans...

**Comment by tgbugs** [comment]
The generalization of this would be health status or disease status or something like that to avoid using a boolean field. You could then accept MONDO/DOID/HP terms an use `HP:0032322 ! Healthy` as the default.

**Comment by UlrikeS91** [comment]
"healthy" could be an option. Still not a fan of adding it at all, but I understand your argument @lzehl and I don't think it would hurt to add it as a term.

**Comment by lzehl** [comment]
Discussion result: add it. For EBRAINS specify curation nagging about how they defined "healthy"

**Comment by lzehl** [comment]
@aeidi89 or @spieschnik could you take this one over? 

SubjectAttribute
+ name: "healthy"
+ definition: "A 'healthy subject' is an individual with no known significant health-related issues. What passes as not-significant health-related issue is defined by the experimental study the individual participates in."

TissueSampleAttribute
+ name: "healthy"
+ definition: "A 'healthy tissue sample' shows no significant pathological abnormalities. What passes as not-significant pathological abnormality is defined by the experimental study the tissue sample is used in."

**Comment by lzehl** [comment]
solved with #416 and #417 (@spieschnik thanks :slightly_smiling_face: )
