### ISSUE TITLE
Change "modality" to "approach"?

### ISSUE THREAD

**Issue by UlrikeS91** [HumanBrainProject/openMINDS_controlledTerms#36]
Based on a discussion with @lzehl and @tgbugs, we would like to rename modalities to approach because it is more descriptive for what it actually is.

@lzehl, anything to add?

**Comment by lzehl** [comment]
@UlrikeS91 I think that's very much it. @apdavison what do you think about this change?

**Comment by apdavison** [comment]
I have no strong opinions either way.

**Comment by lzehl** [comment]
solved in current version
