### ISSUE TITLE
Request for Stimulation Artifact Correction registered as technique 

### ISSUE THREAD

**Issue by maciej-jedynak** [HumanBrainProject/openMINDS_controlledTerms#361]
Metadata for the F-TRACT dataset will need a Stimulation Artifact Correction to be registered as a Technique. 
It sounds very general, but the reference describing details, is the following one:
http://dx.doi.org/10.1016/j.jneumeth.2016.03.002

**Comment by lzehl** [comment]
@maciej-jedynak thank you for the term suggestion. We will add it to the techniques. Based on the article I hope you agree that it would make sense to call this technique "model-based stimulation artifact correction" (vs. the average-based stimulation artifact correction.

**Comment by lzehl** [comment]
@apdavison I already committed the new technique by accident. Could you review the RAW file to make sure that I defined it correctly: https://raw.githubusercontent.com/HumanBrainProject/openMINDS_controlledTerms/v1/instances/technique/modelBasedstimulationArtifactCorrection.jsonld

**Comment by lzehl** [comment]
NOTE: correct instance; add also "stimulation artifact correction" as super-class and "average-based artifact correction" as additional method.

**Comment by Peyman-N** [comment]
It seems good to me :)

**Comment by apdavison** [comment]
In the @id, "modelBasedstimulationArtifactCorrection" should probably be "modelBasedStimulationArtifactCorrection".

**Comment by lzehl** [comment]
@apdavison thanks for spotting this. I will correct it with the PR for moving all analysis techniques from Technique to AnalysisTechnique terminology
