### ISSUE TITLE
Request for Z-scoring registered as a technique

### ISSUE THREAD

**Issue by maciej-jedynak** [HumanBrainProject/openMINDS_controlledTerms#362]
Metadata for the F-TRACT dataset will need a Z-scoring to be registered as a Technique. 

Description (feel free to change):
Z-score (standard score) is the number of standard deviations by which a (non standarized value) differs from population mean.
It is obtained by subtracting population mean from all values and dividing them by population standard deviation.

**Comment by lzehl** [comment]
@maciej-jedynak thank you for suggesting this term. I think the analysis technique should be called "z-score analysis". I will add this to our Technique library. We should also probably add "z-score transformation". 

@apdavison could you please confirm and review the respective PR?

**Comment by Peyman-N** [comment]
The pull request is already merged, so i close this issue
