### ISSUE TITLE
new Technique: phase contrast X-ray tomography

### ISSUE THREAD

**Issue by szafarnia** [HumanBrainProject/openMINDS_controlledTerms#364]
Dear all,
Could you please register “phase contrast X-ray tomography” as a new technique?

**Comment by lzehl** [comment]
I think the following techniques should be registered for this one:

- "phase‐contrast x‐ray computed tomography"
  - synonyms: PCX‐CT, X-ray phase-contrast computed tomography, phase contrast CT, phase‐contrast computed tomography, PCT
  - definition: "'Phase‐contrast x‐ray computed tomography' is a non-invasive x-ray imaging technique for three-dimensional observation of organic matter without application of a contrast medium ([Momose, Takeda, and Itai (1995)](https://doi.org/10.1063/1.1145931))."

- "phase-contrast x-ray imaging"
  - synonyms: phase-sensitive X-ray imaging
  - definition: "'Phase-contrast x-ray imaging' is a general term for different x-ray techniques that use changes in the phase of an x-ray beam passing through an object leading to images with improved soft tissue contrast without the application of a contrast medium. (adapted from [Wikipedia](https://en.wikipedia.org/wiki/Phase-contrast_X-ray_imaging))"
