### ISSUE TITLE
darkmode Logo does not work

### ISSUE THREAD

**Issue by lzehl** [HumanBrainProject/openMINDS_controlledTerms#365]
@ehennestad it seems like the PR #349 did not do the trick. We should have a look at that.

**Comment by skoehnen** [comment]
@lzehl It works for me.
Or ist this not the expected behavior.?

**Dark mode:** 
![Dark_cropped](https://user-images.githubusercontent.com/406428/212557694-752372aa-2a1f-483a-bd98-9ffbd784d279.jpg)

**Light mode:**
![Light_cropped](https://user-images.githubusercontent.com/406428/212557712-17b50288-a330-4f7b-aebd-5afe88fa7c68.jpg)

**Comment by ehennestad** [comment]
Works for me as well. I did remove to link to the image file in the repo, I thought that was a weird link

**Comment by ehennestad** [comment]
Once its confirmed, I can make the change for all the other repos as well

**Comment by lzehl** [comment]
@skoehnen that is the expected behavior, but it does not work in my case. I also checked the code which is fully correct. Which browsers are you using?

**Comment by lzehl** [comment]
@ehennestad the link was there on purpose to guide people to the download of the Logo (if they need it) which is common practice for logos. But we do not necessarily need it.

**Comment by skoehnen** [comment]
> @ehennestad the link was there on purpose to guide people to the download of the Logo (if they need it) which is common practice for logos. But we do not necessarily need it.

@lzehl Unrelated to the dark-mode problem, but do we specify a license for the use of our logo? (Might require a new issue)

**Comment by skoehnen** [comment]
> @skoehnen that is the expected behavior, but it does not work in my case. I also checked the code which is fully correct. Which browsers are you using?

I tried it with Safari Version 16.2 (17614.3.7.1.7, 17614) and Firefox 108.0.1-1

**Comment by lzehl** [comment]
@ehennestad everything in the openMINDS repos is defined under MIT license. We currently do not make an exception for the Logo

**Comment by skoehnen** [comment]
> @ehennestad everything in the openMINDS repos is defined under MIT license. We currently do not make an exception for the Logo

I asked that 😉 

I checked the MIT license
> Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the “Software”), to deal in the Software without ...

The logo would fall under "documentation files" I think, so we would be good 👍

**Comment by skoehnen** [comment]
Quick summary of what we figured out so far:
@lzehl set the Github Appearance to `Theme Mode` -> `Sync with System` and there the night theme with `Light Default` as color scheme. This is technically a "Dark" color scheme but since the background is white, the logo is not visible.

**Comment by skoehnen** [comment]
I am not that up to speed with CSS and how color schemes there are handled there.
Maybe there is a smart way to determine the colour of the background and select the correctly coloured Logo accordingly. 

The easiest workaround from my point of view is to add a black/white outline to the text in the logos, so it would be visible in those edge-cases (Night-Theme with Light colours and Day-Theme with Dark-Colours).

**Comment by lzehl** [comment]
Mh I suggest we just take the solution that @ehennestad implemented for now. We can discuss optimization at a later point in time again.

**Comment by skoehnen** [comment]
Should we close this issue, or keep it open as a reminder?

**Comment by lzehl** [comment]
let's close it for now
