### ISSUE TITLE
Change "datasetType" to "semanticDataType"

### ISSUE THREAD

**Issue by lzehl** [HumanBrainProject/openMINDS_controlledTerms#37]
based on the ontology discussion with @tgbugs we agreed to rename this controlled term and kick-out the GDPR sensitivity part. 

@UlrikeS91 I think we could put the GDPR into the EthicsAssessment. You made that suggestion yesterday and I think you are right. It actually fits in there. We could change entries there to: ("not applicable", "EU compliant, sensitive", "EU compliant, non sensitive") or ("not applicable", "EU compliant, GDPR sensitive", "EU compliant, non sensitive") 

What do you think?

**Comment by UlrikeS91** [comment]
Agreed. I like these best: "not applicable", "EU compliant, sensitive", "EU compliant, non sensitive" 

The other options are a bit inconsistent: "GDPR sensitive" should have (something like) "not GDPR sensitive" as opposite. I would argue that if GDPR is irrelevant enough to leave it out for "non sensitive", then it doesn't really need to be included for "sensitive" either.

**Comment by lzehl** [comment]
@UlrikeS91 thanks for the quick response! I'll update the terminologies then which are now located in https://github.com/HumanBrainProject/openMINDS_instances/tree/master/instances

I'll also change the schema names here and adapt the corresponding reference point in openMINDS_core.

**Comment by lzehl** [comment]
solved in commit (https://github.com/HumanBrainProject/openMINDS_controlledTerms/commit/14428ce632a12b1a374227f0838f35fd364f8743) and commit (https://github.com/HumanBrainProject/openMINDS_core/commit/2293c2975ad50a015006e00855a734e7c86a5eca)

**Comment by lzehl** [comment]
instances update will follow

**Comment by lzehl** [comment]
small note: we chose "not required" in the past, which I left now and did not change to "not applicable"

**Comment by lzehl** [comment]
instances are done as well
