### ISSUE TITLE
new disease terms: tumor, cancer

### ISSUE THREAD

**Issue by lzehl** [HumanBrainProject/openMINDS_controlledTerms#378]
We need the superclasses for all tumor types and cancer.

**Comment by UlrikeS91** [comment]
I think that we should add:

**"neoplasia" (http://purl.obolibrary.org/obo/MONDO_0023370):**
- with "neoplastic disease" and "neoplastic disorder" as synonyms
- definition: "A benign or malignant tissue growth resulting from uncontrolled cell proliferation." or "'Neoplasia' is the uncontrolled, abnormal growth of cells or tissue in the body resulting in a neoplasm or tumor (benign or malignant)."
- Note: "neoplasm" (http://purl.obolibrary.org/obo/MONDO_0005070, which could have "tumor" or "mass" as synonyms) is the result, it's not typically classified as the disease, but we could add "neoplasm" instead if this is easier to understand

**"cancer" (http://purl.obolibrary.org/obo/MONDO_0004992):**
- is a subclass of neoplasia/neoplasm
- definition: "A malignant tissue growth resulting from uncontrolled cell proliferation." or "'Neoplasia' is the uncontrolled, abnormal growth of cells or tissue in the body resulting in a malignant neoplasm or tumor."

This one was a nice source: http://publichealth.lacounty.gov/vet/docs/CancerAnEng.pdf

**Comment by lzehl** [comment]
I have the feeling that MONDO is not very consistent in the definitions / hierarchy of the ontology in this regard. Should maybe use this source with care.

I would also classify tumor more as the result (specification) of the disease. So your suggestions make sense to me. 
But we also registered already glioma and meningioma in diseases as well... 
So for me neoplastic disorder includes benign or malignant tumors. And then each of those have different types. 

Let's discuss this in the next ontology meeting.

**Comment by UlrikeS91** [comment]
> I have the feeling that MONDO is not very consistent in the definitions / hierarchy of the ontology in this regard. Should maybe use this source with care.
> 
> I would also classify tumor more as the result (specification) of the disease. So your suggestions make sense to me. But we also registered already glioma and meningioma in diseases as well... So for me neoplastic disorder includes benign or malignant tumors. And then each of those have different types.
> 
> Let's discuss this in the next ontology meeting.

Yeah, it's hard to differentiate in these cases. Especially with the malignant tumors, the tumor is the name of the disease. In the end, it is also what is being treated/removed and not the disease that caused the tumor to exist in the first place. So, I don't think it would be wrong to add specific tumor types as diseases. If we want to be 100% correct, neoplasia would be the one to add as superclass, but we could also add "neoplasm" to be consistent with the rest (meaning always choosing the mass over the process of obtaining the mass). 
But as you suggested, let's discuss this during our next meeting 🙂

**Comment by lzehl** [comment]
Discussion points (we need to dig into this more):
+ benign neoplasm (not malignant, could be tumorous or not; abnormal cell formations) ???
+ benign tumor (not malignant, typically but inflamed) ???
+ cancer (malignant) (http://purl.obolibrary.org/obo/MONDO_0004992) use name: "malignant neoplasm"
+ cell proliferation disorder (http://purl.obolibrary.org/obo/MONDO_0045024) [superclass of all terms above]

**Comment by lzehl** [comment]
for benign neoplasm refer to http://purl.obolibrary.org/obo/MONDO_0005165 ??

**Comment by lzehl** [comment]
to clarify hierachical order (in the ontology):
+ cell proliferation disorder
    - benign neoplasm
    - malignant neoplasm

**Comment by lzehl** [comment]
@aeidi89 or @spieschnik would you take the PR over for this one?

**Comment by aeidi89** [comment]
Yes, @spieschnik and I will make PRs for these.

**Comment by lzehl** [comment]
@aeidi89 or @spieschnik could you also make a PR for "cell proliferation disorder"

**Comment by lzehl** [comment]
we need to get back to the tumor discussion, but the main term were solved with #402, #403, and #427. I close this issue for now
