### ISSUE TITLE
splitting up digitalIdentifiers into distinct types

### ISSUE THREAD

**Issue by lzehl** [HumanBrainProject/openMINDS_controlledTerms#39]
I discussed again with @olinux : 
For convenience / lowering mistakes / mainenance in using the right / typical digital identifier (and digital identifier schema) for a corresponding instance (e.g., a person, a dataset, a model, etc) it is better to split up the DigitalIdentifier Schema into distinct types (e.g., DOI, ORCID). This would make the need for a DigitalIdentifierSchema obsolete. 

The current DigitalIdentifier schema would become a concept schema (without a type) and extended to (for now) the following distinct types:
- DOI
- ORCID
- GRID
- ISBN

All of them will differ in the type, but follow the same basic (DigitalIdentifier) schema with only two properties now:
- "identifier" (required, count: 1)
- "how to cite" (optional, count: 1)

@apdavison @UlrikeS91 @jagru20 @skoehnen @bweyers @Peyman-N @tgbugs
a) Would you be against this suggestion?
b) There might be more digital identifier types to add: please let me know which ones are missing for our typical purposes.

**Comment by UlrikeS91** [comment]
I don't have any objections. 

Just a question:
With this change, how would I refer to a file in the repository of a dataset, e.g. to have the data descriptor under "fullDocumentation"? I know we have talked about this before, but maybe we could add another digitalIdentifier schema directly to make this easier? We will need this for nearly every dataset. Alternatively, you also allowed to start the discussion around allowing "file(Instances)" to be added as an alternative to a digitalIdentifier ;)

**Comment by lzehl** [comment]
@UlrikeS91 that I've also discussed with @olinux short answer:
- digital identifiers should be official ones
- full documentation needs to get two options for linkedTypes: the DOI (at least) and the File (I think I forgot this one in the core PR ...)

**Comment by lzehl** [comment]
solved in current version
