### ISSUE TITLE
New 'celltype' suggestion

### ISSUE THREAD

**Issue by szafarnia** [HumanBrainProject/openMINDS_controlledTerms#390]
Can "granular neuron" be registered as a new celltype?

**Comment by lzehl** [comment]
@szafarnia yes this can be added as a super class term.

name: "granule neuron"
definition: "The term 'granule neuron' refers to a set of neuron types typically found in granular layers across brain regions whose only common feature is that they all have very small cell bodies. [adapted from [Wikipedia](https://en.wikipedia.org/wiki/Granule_cell)]"
synonym: "granule cell"

@tgbugs this would be a super class I think to a couple of cell types already registered in InterLex. Would you agree with name, definition and synonym?

**Comment by tgbugs** [comment]
Hrm, yeah, we can probably add such a neuron. I think I had it defined at one point but we removed it. I can add it to npo.

**Comment by lzehl** [comment]
TODO, add CellType instance:
name: "granule neuron"
definition: "The term 'granule neuron' refers to a set of neuron types typically found in granular layers across brain regions whose only common feature is that they all have very small cell bodies. [adapted from [Wikipedia](https://en.wikipedia.org/wiki/Granule_cell)]"
synonym: "granule cell"

(links to interlex can be added once the term is available there as well)
@aeidi89 or @spieschnik would you be interested taking this over?

**Comment by spieschnik** [comment]
Yes, I can do the PR

**Comment by apdavison** [comment]
Note that we already have "granule cell" - https://github.com/HumanBrainProject/openMINDS_controlledTerms/blob/v1/instances/cellType/granuleCell.jsonld

**Comment by lzehl** [comment]
@apdavison thank you... I didn't realize. @spieschnik then we do not have to do this PR. Double check though the entry and add the information that is missing. We need to double check as well if we follow the policy we decided on for registering cell types. I think the entry might need to be changed to "granule neuron" with synonym "granule cell"...

**Comment by lzehl** [comment]
@szafarnia instance is updated. You should find it by now in EBRAINS
