### ISSUE TITLE
Separation of "AnalysisTechniques" from "Techniques"

### ISSUE THREAD

**Issue by lzehl** [HumanBrainProject/openMINDS_controlledTerms#415]
The term "AnalysisTechnique" should be reconsidered. We want to decouple more than just "analysis techniques" here. 

What we want to extract is all computational techniques (except for imaging techniques which often involve some kind of computation in order to generate the image(s)). I think this terminology whatever we call it should contain simulation and modeling techniques. So that this terminology includes all techniques that are relevant for the computation extension schemas.

@apdavison @Peyman-N @aeidi89 @ehennestad I need your help here.

A) Should we rename "AnalysisTechnique" to something else? Please make suggestions (I would be okay with "ComputationTechniques")

B) Please go through the candidate list and add what you think is missing there or what should be kept in the "Techniques" terminology: https://docs.google.com/spreadsheets/d/1dh3VyZ2GzFUn9ROgWglf8O_Xbiv1xGC9PMEycyXPumE/edit?usp=sharing

**Comment by tgbugs** [comment]
```
data -> data computational
real -> data "measurement"
real -> real ???
data -> real actualization
```
are the criteria I would use, so anything that does `data -> data` should always be computational and data includes literally anything that is symbolic rather than trapped out in the real world, e.g. code also counts as "data" in this context
```
symbolic -> symbolic computational
physical -> symbolic "measurement"
physical -> physical ???
symbolic -> physical actualization
```

**Comment by lzehl** [comment]
@tgbugs @apdavison we should find a common strategy here soon so that we can do the cleanup for EBRAINS.

**Comment by lzehl** [comment]
Leave the terminology term for now to "AnalysisTechnique"

**Comment by lzehl** [comment]
Go through list to claim "yes" "no" and "maybe" for separating techniques into that terminology

**Comment by lzehl** [comment]
@apdavison @Peyman-N @aeidi89 @ehennestad  I went through the list and made first yes/no/maybe suggestions. https://docs.google.com/spreadsheets/d/1dh3VyZ2GzFUn9ROgWglf8O_Xbiv1xGC9PMEycyXPumE/edit?usp=sharing
