### ISSUE TITLE
New term suggestion: Postnatal development

### ISSUE THREAD

**Issue by ingrre** [HumanBrainProject/openMINDS_controlledTerms#422]
I added postnatal development as a keyword (Term suggestion) in the KG Editor.

Label: postnatal development
Definition: the act or process of growing, progressing, or developing after birth
Interlex identifier https://uri.interlex.org/base/ilx_0472309
Is keyword of 2  Dataset versions: Parvalbumin mouse development, Calbindin mouse development
ID: 81076c7d-1e78-4418-aa92-a62eb598e9f2

Was not sure what to do with this, so I thus just update you here and wait for further instructions.

**Comment by lzehl** [comment]
@ingrre thanks for suggesting this term for the controlled terminologies. I'll bring it up in the next openMINDS/ontology meeting. because this term does not fit in any of our current parent terminologies. We will have to discuss it. I'll get back to you as soon as we decide something.

**Comment by tgbugs** [comment]
Should be a life cycle stage that matches this. They are mapped to the Theirler stages (spelling?).

**Comment by UlrikeS91** [comment]
Was added https://github.com/openMetadataInitiative/openMINDS_instances/blob/main/instances/latest/terminologies/unitOfMeasurement/postnatalDay.jsonld
