### ISSUE TITLE
New Disease

### ISSUE THREAD

**Issue by archgogo** [HumanBrainProject/openMINDS_controlledTerms#438]
name: trigeminal neuralgia
definition: Trigeminal neuralgia is sudden, severe facial pain.
interlex identifier: https://neuinfo.org/interlex/view/ilx_0758102?searchTerm=Trigeminal%20neuralgia

**Comment by lzehl** [comment]
@archgogo thanks for requesting this. It is in process #439

**Comment by aeidi89** [comment]
@archgogo #439 has now been approved and I'll close this issue.
