### ISSUE TITLE
Add new property to all controlledTerms to link to KnowledgeSpace

### ISSUE THREAD

**Issue by UlrikeS91** [HumanBrainProject/openMINDS_controlledTerms#44]
Decided on during an external discussion with @tgbugs, Mathew (don't know his GitHub) and @lzehl: We will make some major changes to the controlledTerms schemas.   
**1. Change "OntologyIdentifier" to "PreferredOntologyIdentifier".** The preferred ID (as stated on InterLex) will be used here.
**2. Add a new property called "InterlexIdentifier".** This will also be an ontology ID, but specifically only InterLex IDs.  
**3. Add another new property called "KnowledgeSpaceLink".** This will link to the corresponding KS wiki page for each controlledTerm instance. 

What should be shown/used in the Knowledge Graph Search is the the "KnowledgeSpaceLink" redirecting the user to the KS wiki page for the controlledTerm instance. 
(FYI @olinux)

Example for an "UBERONParcellation":
```
[...]
"name": "thalamus",
[...]
"preferredOntologyIdentifier": "http://purl.obolibrary.org/obo/UBERON_0001897",
"interlexIdentifier": "http://uri.interlex.org/ilx_0111657",
"knowledgeSpaceLink": "https://knowledge-space.org/wiki/UBERON:0001897#thalamus",
[...] 
```

**Comment by lzehl** [comment]
@UlrikeS91 we should maybe include "synonym" as new property in this PR as well. In most cases we can get them from the ontologies (if available) and in other cases it might just hold useful abbreviations (e.g., for units). Or should we be explicit for the abbreviation for units ? @tgbugs & @olinux what is your opinion here?

**Comment by olinux** [comment]
hm, to be honest, I'm hesitating a little to have these hard-coded "natures" of identifiers in the property name... it seems like it makes it hard to be reused for others (that are not using interlex / knowledge space / ... 
wouldn't it be better to just have "additionalIdentifiers" which are having typed entries (as we have it for DOI / SWHID / ...)?

**Comment by lzehl** [comment]
They are different in nature (specific ontology ID, wiki entry with integrated ontologies, interlex with integrated ontologies) so running them under additionalIdentifier might be not correct. But I'm open to making this more generic (as long as for EBRAINS we could emphasize the interlex and KS link on a simple landing page for the controlled instances?).

**Comment by lzehl** [comment]
@tgbugs you have ideas?

**Comment by tgbugs** [comment]
We could make it more generic, but I think we were imagining a fairly direct mapping to landing pages for controlled terms. Additional links would work, but I think you will want a link type or something of that nature so that you can pull out specific identifiers without having to parse the url. So it would become an additional links field and then you would have an enum of types e.g. `["uberon", "interlex", "knowledgespace"]` etc. I also suggest having a synonyms field just because I suspect you will want/need it at some point and may not want to populate it from the ontology.
