### ISSUE TITLE
new technique: diffusion spectrum imaging (DSI)

### ISSUE THREAD

**Issue by lzehl** [HumanBrainProject/openMINDS_controlledTerms#444]
@tgbugs cf. https://onlinelibrary.wiley.com/doi/10.1002/mrm.20642
I want to be sure that this is not a synonym of what we already have

**Comment by UlrikeS91** [comment]
I'm closing this one, same as this one: https://github.com/openMetadataInitiative/openMINDS_instances/issues/98
