### ISSUE TITLE
ExApproaches: Renaming experimental approaches to avoid mixing "field of study" with "experimental approach".

### ISSUE THREAD

**Issue by aeidi89** [HumanBrainProject/openMINDS_controlledTerms#446]
Sprung out of #377

TLDR: 

All experimental approaches in openMINDS (e.g., histology, electrophysiology etc). should be renamed to xxx approach for consistency (see discussion in #377). The previous naming should be included as a synonym.

**Comment by UlrikeS91** [comment]
This has been discussed previously and we decided that openMINDS will not use the "xxx approach" names, only when there is no alternative. I don't remember the exact reason, but @lzehl could probably elaborate. I will close this issue, since we will not change the names.

**Comment by UlrikeS91** [comment]
Also, there is generally no need to adhere to the term used in an ontology. We are linking to them and adding the alternatives as synonyms. This way we can decide for openMINDS what we would like to use.
