### ISSUE TITLE
new technique requests

### ISSUE THREAD

**Issue by lzehl** [HumanBrainProject/openMINDS_controlledTerms#47]
@tgbugs : we would like to add the following instances. Would you agree?
 (some of them might only not exist in our list, but you have them already)

"NEW" TECHNIQUES SUGGESTIONS:    

1. **calcium imaging**
2. **fiber photometry**
3. **pupillometry** 
4. **electrooculography**
5. **video-oculography**
6. **eye-attached tracking**
7. **ultrasound imaging**
8. **virus transfection** OR **virus-mediated transfection**
9. **neuronal tracing**
10. **retrograde tracing**
11. **voltammetry**
12. **cryopreservation**
13. **cryofixation**
14. **manual sectioning** (if tissue was cutted by hand with a knife to smaller pieces)

**Comment by UlrikeS91** [comment]
Note: 4. electrooculography already exists as a controlledTerm/technique

Continuation of @lzehl's list:

15. 3D computer graphic modeling
16. 3D scanning
17. beta-galactosidase staining
18. connectivity based parcellation technique
19. drifting grating visual stimulation
20. electromyography
21. figure-ground visual stimulation
22. headpost implantation surgery
23. high-speed video recording
24. immunoprecipitation
25. implant surgery
26. injection
27. intracranial electroencephalography
28. mass spectrometry
29. morphometry
30. multi-compartement modeling
31. natural image visual stimulation
32. natural sound stimulation
33. non-rigid motion correction
34. perfusion fixation technique
35. perturbational complexity index analysis
36. photon stimulation technique
37. pressure (micro) injection
38. rule-based modeling
39. scattered light imaging
40. seed-based correlation analysis
41. sonography
42. static grating visual stimulation
43. stimulation
44. structural covariance analysis
45. tetrode extracellular electrophysiology
46. video tracking
47. voxel-based morphometry

Some additional ones that may be up for discussion:

48. (ligand) binding affinity measurement
49. communication profiling
50. dye filling
51. light extinction measurement
52. nonlinear image registration

@tgbugs Any comments? ;)

**Comment by tgbugs** [comment]
A bunch of these are already in the ontology, will need to do a more thorough check (this format is not easy to review).

**Comment by UlrikeS91** [comment]
I'll close this issue for now. We have added (I think) all of them for now (https://github.com/HumanBrainProject/openMINDS_controlledTerms/pull/48) but can be changed later on if necessary.
