### ISSUE TITLE
Reassessing techniques

### ISSUE THREAD

**Issue by MaaikevS** [HumanBrainProject/openMINDS_controlledTerms#70]
Hi,

There are a few controlled terms for techniques that I think need to be reassessed and perhaps 'cleaned up'. 

**1) Fixation / perfusion**
Currently there are a number of techniques that only differ slightly in my opinion.
- fixation technique
- tissue fixation technique
- perfusion fixation technique
- intracardial perfusion technique
- perfusion technique

I would reduce this to "fixation technique" and "perfusion technique". 

Perfusions are typically done intracardially (I would not know how else to do it), first a saline solution is perfused and then a fixative. You would never perfuse with just a fixative. "Perfusing with fixative only" does not work and you would be better off dumping the tissue in a fixative immediately.

**2) contrast enhancement vs contrast enhancement technique**
It is not clear what the difference is, so I would just keep one and not both.

**3) meta-analytic modeling vs meta-analytic modelling**
Same thing, just different spelling

**4) patch clamp vs patch clamp technique**
It is not clear what the difference is, so I would just keep one and not both.

There are probably a few more that I would probably suggest to have another look at, but they might be a bit more involved.

**Comment by lzehl** [comment]
@MaaikevS thank you for creating this issue. Here my assessment:

**for 1)** I agree. I think a reduction to "fixation technique" and "perfusion technique" is wise and would avoid inconsistencies.  @tgbugs & @UlrikeS91 what do you think?

**For 2 - 4:** these seem to be EBRAINS KG issues. @olinux there seems to be an issue with deprecated instances. Could you have look why deprecated instances are still available? Let me know if I can help fixing the issue.

for 2) That is indeed an error that we overlooked in the EBRAINS KG. In openMINDS (GitHub instances) we only kept "contrast enhancement".

for 3) That is indeed an error that we overlooked in the EBRAINS KG. We actually kept in openMINDS (GitHub instances) "meta-analytic connectivity modeling".

for 4) That is indeed an error that we overlooked in the EBRAINS KG. In openMINDS (GitHub instances) we only kept "patch clamp".

**Comment by UlrikeS91** [comment]
> **for 1)** I agree. I think a reduction to "fixation technique" and "perfusion technique" is wise and would avoid inconsistencies. @tgbugs & @UlrikeS91 what do you think?

I would disagree to some extend. It is true that the most common use case for use will be an intracardial perfusion (fixation) technique, where an organism is perfused first with saline and then with a fixative via the heart. But from a semantic perspective, neither "perfusion" nor "fixation" on their own express this. There is much more to it. 

perfusion (medical definition): the act of pouring a liquid over or through the tissue of a particular organ
fixation (medical definition): the process of preserving something in a laboratory using a special liquid

A quick Google search also resulted in e.g. an in situ brain perfusion technique (https://link.springer.com/protocol/10.1385/1-59259-419-0:209) where no fixative is used (and also isn't done intracardially). And, out of my own experience, following the perfusion fixation, there is usually an additional fixation step. 

So, I'm not sure what will be the best solution but I do agree that a clean up of the terms would be useful. 

**1. fixation technique vs. tissue fixation technique:** not sure if there is any non-tissue that can be fixated; maybe one of them is enough?
**2. perfusion fixation technique vs. perfusion technique:** I'm not aware of any use cases in the EBRAINS KG, where we would need "perfusion" (as a non-fixation technique); maybe we could remove that one and rather see if any use case every comes up, where the fixation isn't the point?
**3. perfusion (fixation) technique vs. intracardial perfusion technique:** I don't believe that all perfusions are done intracardial, but it is pretty standard for rodents at least. I would like to keep "intracardial perfusion (fixation)". I would be fine with kicking out "perfusion (fixation)" instead and rather add more specific techniques along the way, though.

**Comment by lzehl** [comment]
@UlrikeS91 thanks for your feedback.

to your 1) lets only keep "fixation technique"; what is fixated can be specified in the protocol
to your 2) I see your point. Lets keep both then but we should add definitions for these cases so that people are aware of the difference.
to your 3) I would argue for only keeping "perfusion fixation technique" and describe how the perfusion was done in the protocol

@tgbugs your thoughts? @MaaikevS would that solve your issue?

**Comment by tgbugs** [comment]
Let's start by adding definitions to see if that helps.

**Comment by MaaikevS** [comment]
To come back to this issue. @lzehl @UlrikeS91 

1) **Fixation technique:**
Suggested definition:
Fixation is a technique to preserve tissues permanently as faithfully as possible compared to the living state.
Suggested description: 
Fixation is a two-step process in which 1) all normal life functions are terminated and 2) the structure of the tissue is stabilized (preserved). The fixation of tissue can be achieved by chemical or physical (e.g. heating, freezing) means.

2) **Perfusion fixation technique**
Suggested definition:
Perfusion fixation is a technique that uses the vascular system to distribute fixatives throughout tissue.

**Perfusion technique**
Suggested definition:
Perfusion is a technique to distribute fluid through the circulatory system or lymphatic system to an organ or a tissue.

3) I am still unsure how much intracardial perfusion is adding. I am saying this because some people describe the same method as transcardial perfusion. I would argue they are typically same or at least so similar that I don't think we are doing ourselves a favor by 'dispersing' the linkages over multiple nodes (for comparability/findability). 
I am happy to go with whatever the majority wants of course, I am just challenging this because of the fact that datasets with the same methods might not actually be connected in the end. We could of course make the perfusion fixation technique more specific by adding a new technique such as "perfusion fixation technique (via heart)". This would then cover both intracardial and transcardial, which I would prefer.

**Comment by MaaikevS** [comment]
@tgbugs Could you please have a look at this again? Thank you!

**Comment by lzehl** [comment]
result of discussion with @tgbugs, 

Keep: 
+ fixation technique
+ perfusion fixation technique
+ perfusion technique
+ intracardiac perfusion technique (with intracardial perfusion technique, transcardial perfusion technique)

Delete:
+ tissue fixation technique

Add:
+ diffusion fixation technique
+ intracardiac perfusion fixation technique (see synonyms above)
