### ISSUE TITLE
Biological Sex - add something like "unknown"

### ISSUE THREAD

**Issue by UlrikeS91** [HumanBrainProject/openMINDS_controlledTerms#72]
Since "biologicalSex" is a required property for subject(Group)s and tissueSample(Collection)s, I was wondering if we could introduce something along the lines of "unknown". 

I know that we did not want to leave this as an option because it should be known, but there are still cases where this information maybe cannot be provided.

My bigger concern is for the cases where the sex in fact cannot be determined yet, basically most stages before birth (e.g. an embryo).

I can see a few options for solving this:
1. Make "biologicalSex" optional (not preferred because it's not differentiating between "forgotten to fill in" vs. "not knowing but should have" vs. "really not possible to determine yet")
2. Add "unknown" as a controlledTerm (disadvantage: "not knowing but should have" vs. "really not possible to determine yet" would be collected under one term)
3. Add "unknown" & "undeterminable" (or similar) as controlledTerms - unknown for "not knowing but should have" & undeterminable for "really not possible to determine yet"

@lzehl? Who else?

**Comment by lzehl** [comment]
@UlrikeS91 thanks for bringing this up. I already expected that this will bite us :)

I still do not want to have "unknown" in as in "I do not know". I think we should not support this actively. Therefore I would go with solution one PLUS:
"not possible to determine yet" is another issue which we could cover in addition for biologicalSex. 
I would go for this with the term "not detectable yet".

**Comment by lzehl** [comment]
If we introduce "unknown" we need to do that for basically all fields to distinguish between "not filled yet" and "will never be filled" which I do not want to do via adding "unknown" to all terminologies... If we want to tackle this, we should do this in a smarter more generalized way. @olinux any idea? (not an urgent issue)

**Comment by UlrikeS91** [comment]
> @UlrikeS91 thanks for bringing this up. I already expected that this will bite us :)
> 
> I still do not want to have "unknown" in as in "I do not know". I think we should not support this actively. Therefore I would go with solution one PLUS: "not possible to determine yet" is another issue which we could cover in addition for biologicalSex. I would go for this with the term "not detectable yet".

I agree. I would also prefer to avoid "unknown" aka "I don't know". The other case needs to be covered, though. So, I like your suggestion/extension to my suggestion. I'm not a fan of "not detectable yet". It's very much true, because this is the reason the sex cannot be stated for some subjects, but since it says "yet" I get the feeling of "but it's possible later". Could we just call it "not detectable"? In the context of the subjectState, I would say that the temporal aspect is covered anyway.

**Comment by lzehl** [comment]
yes. fine with me

**Comment by UlrikeS91** [comment]
I just closed this issue and notice that we wanted to change biologicalSex to being optional, didn't we @lzehl?
