### ISSUE TITLE
request for new technique

### ISSUE THREAD

**Issue by ingrre** [HumanBrainProject/openMINDS_controlledTerms#76]
pressure injection; injection technique where pressure is used to inject a substance

request for new cell type: basket cell;  inhibitory GABAergic interneurons of the brain, found throughout different regions of the cortex and cerebellum

**Comment by lzehl** [comment]
@ingrre thanks for those suggestions

I wonder what you mean with "pressure injection" precisely. Are not all injection substences injected using pressure? Do you mean high-pressure?

For "basket cell" would you like to enter a parent class for "basket cells" or would those two be sufficient?
+ neocortex basket cell (http://uri.interlex.org/base/ilx_0107351)
+ cerebellum basket cell (http://uri.interlex.org/base/ilx_0101964)

**Comment by UlrikeS91** [comment]
> I wonder what you mean with "pressure injection" precisely. Are not all injection substences injected using pressure? Do you mean high-pressure?

No, not all injections are done using pressure. We even have one of the alternatives already in the system: https://github.com/HumanBrainProject/openMINDS_controlledTerms/blob/v1/instances/technique/iontophoreticMicroinjection.jsonld

So, pressure injection would be very useful to have (I also need that one for my own datasets 😆), and it exists in the method ontology: http://uri.interlex.org/ilx_0739660. 


> For "basket cell" would you like to enter a parent class for "basket cells" or would those two be sufficient?
> 
> * neocortex basket cell (http://uri.interlex.org/base/ilx_0107351)
> * cerebellum basket cell (http://uri.interlex.org/base/ilx_0101964)

@ingrre and I talked quickly about this. Cerebellum basket cell will work perfectly for her use case. I would suggest to also add "basket cell". Will probably be useful for other datasets 😉

**Comment by ingrre** [comment]
Thanks for your swift replies. Pressure injection as a technique is also described in this paper: https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4828981/

**Comment by lzehl** [comment]
So you would like to have an additional "child" term for `injection` which is already part of the terminology. 
That is fine with me then. 

I will also enter all basket cell terms :) 

@UlrikeS91  and @ingrre thanks for explaining a bit more :grin:

**Comment by lzehl** [comment]
@UlrikeS91 I'm doing the PR unless you already started?

**Comment by UlrikeS91** [comment]
> @UlrikeS91 I'm doing the PR unless you already started?

Nope, go ahead ☺️
