### ISSUE TITLE
reassess spatialRegistration vs imageRegistration

### ISSUE THREAD

**Issue by lzehl** [HumanBrainProject/openMINDS_controlledTerms#81]
@tgbugs Is this a synonym or something different?

**Comment by tgbugs** [comment]
Yes, these are synonyms.

**Comment by lzehl** [comment]
@MaaikevS & @UlrikeS91 this means that we need to merge the terms, keeping "image registration" with "spatial registration" as synonym. For EBRAINS this means quite a lot of cleanup.
