### ISSUE TITLE
adding technique: cryosectioning

### ISSUE THREAD

**Issue by lzehl** [HumanBrainProject/openMINDS_controlledTerms#90]
@tgbugs I'd like to add "cryosectioning" as technique. what do you think?
(@MaaikevS)

**Comment by UlrikeS91** [comment]
Follow-up question: We have 'microtome sectioning' & 'vibratome sectioning'. I know that microtome sectioning can be done both as 'cryo-microtome sectioning'/'freezing microtome sectioning', as well as without cryo (what ever we would call that). Would we need to add those terms as well then?

**Comment by lzehl** [comment]
I know there is 'cryo-microtome sectioning',the question is is the cryosectioning also peformed with an other device than a microtome? :sweat_smile:

**Comment by UlrikeS91** [comment]
> I know there is 'cryo-microtome sectioning',the question is is the cryosectioning also peformed with an other device than a microtome? 😅

Yes, I think so...

**Comment by lzehl** [comment]
then I think "cryosectioning" could be a nice parent term in case the device should not be specified?

**Comment by MaaikevS** [comment]
I would say a cryostat and a microtome are two different pieces of equipment.

**Comment by lzehl** [comment]
@MaaikevS "cryostat" what do you mean?

**Comment by lzehl** [comment]
So from what I read crysectioning is indeed in most cases cryo-microtome sectioning which is done with a microtome insight a cryostat

**Comment by MaaikevS** [comment]
"A cryostat (from cryo meaning cold and stat meaning stable) is a device used to maintain low cryogenic temperatures of samples or devices mounted within the cryostat. " 

In the dataset that initiated this discussion, they clearly state that they used a cryostat to section the tissue. 
"the brains were cut coronally into 40 µm thick sections on a cryostat (Leica, Germany). "

**Comment by lzehl** [comment]
And a cryostat seems to be always build with a microtome

**Comment by MaaikevS** [comment]
That is a fair assessment then. I guess adding cryo to the microtome sectioning might be sufficient then

**Comment by lzehl** [comment]
:+1: then we can do the PR

**Comment by tgbugs** [comment]
I will add cryosectioning technique. Microtomy technique already exists  http://uri.interlex.org/base/ilx_0739422 .

**Comment by UlrikeS91** [comment]
Conclusion:
- add "cryosectioning"
- update "microtome sectioning" with http://uri.interlex.org/base/ilx_0739422 as InterLex ID & "microtomy" as synonym
