### ISSUE TITLE
Request: new cell types and techniques

### ISSUE THREAD

**Issue by ingrre** [HumanBrainProject/openMINDS_controlledTerms#94]
Add cell types: 
stellate cell 
parvalbumin cell
cholecystokinin cell 
cholinergic neuron
dopaminergic neuron
spiny projection neuron 
somatostatin expressing neuron
vasoactive-intestinal peptide expressing neuron

Add technique: 
infrared differential interference contrast (IR-DIC) microscopy (see dataset "Electrophysiological recordings of striatal low threshold-spiking interneuron") 
ABC staining (avidin-biotin complex kit to visualise biotin-containing substances in tissue (histochemistry)

**Comment by tgbugs** [comment]
Is there more specific information about the follow cell types?
1. stellate cell, which brain region?
2. spiny projection neuron, which brain region? are these medium spiny neurons from L4 or striatum?

I will add the abstracted common usage types for PV, CCK, SST, and VIP.

For techniques
http://uri.interlex.org/base/ilx_0739494 IR-DIC already exists
We can add ABC staining, if you have the identifier for the kit we can use that as well.

**Comment by UlrikeS91** [comment]
conclusion:

requested cellTypes | controlledTerm/comment | synonyms | ontology ID
---|---|---|---
stellate cell | stellate cell | - | -
stellate cell | @ingrre maybe a brain region specific stellate cell  would be more suitable for your case? e.g. "cerebellum stellate cell" | - | http://uri.interlex.org/ilx_0101975
parvalbumin cell | parvalbumin expressing cell | PV+ cell, parvalbumin expressing neuron, etc. | - 
cholecystokinin cell | cholecystokinin expressing cell | CCK+ cell, cholecystokinin expressing neuron, etc. | -  
cholinergic neuron | cholinergic neuron | - | http://uri.interlex.org/ilx_0102131
dopaminergic neuron | dopaminergic neuron | - | http://uri.interlex.org/ilx_0103395
spiny projection neuron | depends on @ingrre answer | - | -  
somatostatin expressing neuron | somatostatin expressing cell | SST+ cell, somatostatin expressing neuron | -
vasoactive-intestinal peptide expressing neuron | vasoactive-intestinal peptide cell | VIP+ cell, vasoactive-intestinal peptide expressing neuron | -

requested techniques | controlledTerm/comment | synonyms | ontology ID
---|---|---|---
infrared differential interference contrast (IR-DIC) microscopy | infrared differential interference contrast video microscopy | IR DIC video microscopy, IR-DIC | http://uri.interlex.org/ilx_0739494
ABC staining | avidin-biotin complex staining | - | -



@ingrre if there are any of the terms we will add that do not fit your needs, please let us know.

**Comment by lzehl** [comment]
@UlrikeS91 question/comments:  
a) for "stellate cell" didn't you argue that "stellate neuron" would be the better term for this one? but maybe I misunderstood 
b) for "spiny projection neuron" we should go the same way as for "stellate"; register also the super-class, and the region-specific ones in addition
c) for ABC staining we should add ABC staining as synonym, no? (I think you just missed that one in the table)

**Comment by UlrikeS91** [comment]
Update:
@lzehl is right. I added "stellate neuron" and also added "cerebellum stellate neuron" (needed or not, doesn't matter). I've added "spiny neuron" because projection is not a cell type quality in itself. It only expresses that this is a cell connected to another cell injected by a tracer (roughly, the exact definition might be different). @ingrre if you need a more specific "spiny neuron" type, please let me know. We can add more of course. 
ABC staining is added as a synonym. Just forgot to add it in the list above.

**Comment by ingrre** [comment]
Wonderful, thank you so much. Cerebellar stellate cells was what I needed for this exact case, so that's great. 

I think spiny projection neurons (SPNs) are in fact a thing. The direct pathway SPNs (dSPNs) predominantly express the dopamine D1 receptor (D1R), and the indirect pathway SPNs (iSPNs) express the dopamine D2 receptor , according to this paper: https://elifesciences.org/articles/58544. The dataset in question is: https://doi.org/10.25493/YP8N-HD2

**Comment by ingrre** [comment]
While at it, could we add "video recording" as technique too? Only "high speed video recording" exists at the moment, and I am not sure that would be correct in this case (https://doi.org/10.25493/9WBS-PK4)

**Comment by UlrikeS91** [comment]
> While at it, could we add "video recording" as technique too? Only "high speed video recording" exists at the moment, and I am not sure that would be correct in this case (https://doi.org/10.25493/9WBS-PK4)

Based on the data descriptor and the following sentence, "The interaction time with the stranger mouse was recorded by the **video-tracking system** (ANY-maze, Stoelting Co, IL, US).", I would say that the technique "video tracking" should be best suitable, which already exists as a technique. 

If anything I would actual say that "high-speed video recording" may need to be remove, @lzehl & @tgbugs? I found "video recording" in InterLex (http://uri.interlex.org/ilx_0487420) and this seems to be closer related to the output (aka the recording file) than a technique that was used to record, right? Is "high-speed video recording" any different from that?

**Comment by UlrikeS91** [comment]
@ingrre requested "Purkinje cell" offline. This was a no-brainer and I added it to the PR (#98).

**Comment by UlrikeS91** [comment]
> Wonderful, thank you so much. Cerebellar stellate cells was what I needed for this exact case, so that's great.
> 
> I think spiny projection neurons (SPNs) are in fact a thing. The direct pathway SPNs (dSPNs) predominantly express the dopamine D1 receptor (D1R), and the indirect pathway SPNs (iSPNs) express the dopamine D2 receptor , according to this paper: https://elifesciences.org/articles/58544. The dataset in question is: https://doi.org/10.25493/YP8N-HD2

I'm sorry! I must have misunderstood that one...Google help, though. Wikipedia says that "medium spiny neurons" are a synonym for "spiny projection neurons".  I assume you are looking for the ones in the striatum? If so, I could offer you "striatum medium spiny neurons" (http://uri.interlex.org/ilx_0784362). 
Some alternatives: 
- "Neostriatum direct pathway spiny neuron" (http://uri.interlex.org/ilx_0107404)
- "Neostriatum indirect pathway spiny neuron" (http://uri.interlex.org/ilx_0107405)

@ingrre if you click on the links, you can read the definitions that InterLex states. Which one(s) would you like to have?

**Comment by ingrre** [comment]
Great! Thanks. Can I have both? Both direct and indirect are used in my dataset (https://doi.org/10.25493/YP8N-HD2)

**Comment by UlrikeS91** [comment]
> Great! Thanks. Can I have both? Both direct and indirect are used in my dataset (https://doi.org/10.25493/YP8N-HD2)

I've added both to PR #98.
